___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lab, Session</p><h1>

## A sample solve in Linear Algebra using NumPy

In [1]:
import numpy as np

In [ ]:
# 3*x + y = 9
# x + 2*y = 8

In [3]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

In [4]:
a

array([[3, 1],
       [1, 2]])

In [5]:
b

array([9, 8])

In [6]:
np.linalg.solve(a, b)

array([2., 3.])

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [7]:
# create a range
# arguments: start, stop, step
x = np.arange(0, 10, 1)

x



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y = np.arange(-1, 1, 0.2)
y

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

#### linspace and logspace

In [9]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [12]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

#### random data

In [15]:
# uniform random numbers in [0,1]
# seed() must be underlined to the student. what is it used for?
np.random.seed(0)
np.random.rand(5,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

In [1]:
import numpy as np

In [10]:
np.random.seed(0)
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [12]:
np.random.rand(3,3)

array([[0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985]])

In [13]:
np.random.seed(0)
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [14]:
np.random.rand(3,3)

array([[0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985]])

In [17]:
np.random.rand(5,5)

array([[0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236],
       [0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358]])

In [6]:
# standard normal distributed random numbers
np.random.randn(3,3)

array([[-0.36433431, -0.67877739, -0.35362786],
       [-0.74074747, -0.67502183, -0.13278426],
       [ 0.61980106,  1.79116846,  0.17100044]])

#### diag

In [15]:
# a diagonal matrix
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
# diagonal with offset from the main diagonal
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [18]:
np.diag([1,2,3,4], k=2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Manipulating arrays

### Fancy indexing

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [19]:
B = np.array([i for i in range(5)])
B

array([0, 1, 2, 3, 4])

In [23]:
B = np.array(range(5))
B

array([0, 1, 2, 3, 4])

In [21]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [26]:
row_mask = np.array([1, 0, 1, 0, 0], dtype = bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [28]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [29]:
mask = (5 < x) & (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [30]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

## Functions for extracting data from arrays and creating arrays

### ``where``

The index mask can be converted to position index using the `where` function

In [31]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [33]:
indices = np.where(mask)
indices

(array([11, 12, 13, 14], dtype=int64),)

In [34]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

In [35]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

### ``diag``

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [37]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [1, 2, 3, 4], [5, 6, 7, 8,]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.diag(A)

array([1, 6, 3, 8])

In [39]:
np.diag([1, 6, 3, 8])

array([[1, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 8]])

In [40]:
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
np.diag(A, k=1)

array([2, 7, 4])

In [42]:
np.diag(A, k=3)

array([4])

### ``take``

The `take` function is similar to fancy indexing described above:

In [43]:
v2 = np.arange(-3, 3)
v2

array([-3, -2, -1,  0,  1,  2])

In [44]:
# fancy indexing
row_index= [1, 3, 5]
v2[row_index]

array([-2,  0,  2])

In [45]:
v2.take(row_index)

array([-2,  0,  2])

But `take` also works on lists and other objects:

### ``choose``

Constructs an array by picking elements from several arrays:

In [48]:
which = [1, 0, 1, 2]
choices = [[-2, -3, -4, -5], [6, 7, 8, 9], [1,2,3,4]]

In [49]:
np.choose(which, choices)

array([ 6, -3,  8,  4])