___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [1]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [2]:
pd.Series([10, 88, 3, 4, 5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [3]:
ser = pd.Series([10, 88, 3, 4, 5])

In [4]:
ser

0    10
1    88
2     3
3     4
4     5
dtype: int64

### Basic Attributes of Series

In [5]:
type(ser)

pandas.core.series.Series

In [6]:
ser.dtype

dtype('int64')

In [7]:
ser.size

5

In [8]:
ser.ndim

1

In [9]:
ser.values

array([10, 88,  3,  4,  5], dtype=int64)

In [10]:
for i in ser.values:
    print(i)

10
88
3
4
5


In [11]:
[i for i in ser.values]

[10, 88, 3, 4, 5]

In [ ]:
# [10, 88, 3, 4, 5]

In [12]:
ser.head(3)

0    10
1    88
2     3
dtype: int64

In [13]:
ser.tail(3)

2    3
3    4
4    5
dtype: int64

In [15]:
[i for i in string]

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [14]:
string = "clarusway"

pd.Series([i for i in string])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [16]:
labels = ["a", "b", "c"]
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {"a" : 10, "b" : 20, "c" : 30}

### **Using Lists**

In [17]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [18]:
pd.Series(data = my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [19]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

### **Using NumPy Arrays**

In [20]:
arr

array([10, 20, 30])

In [21]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [23]:
labels

['a', 'b', 'c']

In [22]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [24]:
d

{'a': 10, 'b': 20, 'c': 30}

In [25]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series(d, ["w", "c", "d"])

w     NaN
c    30.0
d     NaN
dtype: float64

### Data in a Series

A pandas Series can hold a variety of object types:

In [27]:
labels

['a', 'b', 'c']

In [28]:
pd.Series(data = labels)

0    a
1    b
2    c
dtype: object

In [29]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [30]:
mix_data = [1, "cat", True]

In [31]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

## Sorting Index | Sorting Values | Check Data if it is in the pd.Series

### [`.sort_index`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-series-sort_index.ipynb) | [`.sort_values`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-series-sort_values.ipynb) | [`.isin`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-series-isin.ipynb)

***



## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [32]:
ser1 = pd.Series([1,2,3,4], index = ["USA", "Germany", "USSR", "Japan"])

In [33]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [34]:
ser2 = pd.Series([1,2,5,4], index = ["USA", "Germany", "Italy", "Japan"])

In [35]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [36]:
ser1["USA"]

1

Operations are then also done based off of index:

In [37]:
ser3 = pd.Series(data = labels)

In [38]:
ser3

0    a
1    b
2    c
dtype: object

In [39]:
ser3[0]

'a'

In [41]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [42]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [40]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

### Indexing Examples

In [43]:
a = np.array([1, 2, 33, 444, 75])

In [44]:
a

array([  1,   2,  33, 444,  75])

In [45]:
panser = pd.Series(a)

In [46]:
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [47]:
panser[0]

1

In [48]:
panser[0:3]

0     1
1     2
2    33
dtype: int32

In [49]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [51]:
ser1["USA" : "USSR"]

USA        1
Germany    2
USSR       3
dtype: int64

### pandas_series[index] | pandas_series[[indices, indices...]]

In [52]:
panser = pd.Series([121,200,150,99], index = ["ali", "veli", "gul", "nur"])

In [53]:
panser

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [54]:
panser["ali"]

121

In [55]:
panser[0]

121

In [56]:
panser[["veli", "nur"]]

veli    200
nur      99
dtype: int64

In [57]:
panser[0:3]

ali     121
veli    200
gul     150
dtype: int64

In [58]:
panser["ali" : "nur"]

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [59]:
panser["ali" : "gul"]

ali     121
veli    200
gul     150
dtype: int64

### Several Selecting Attributes

In [60]:
panser.index

Index(['ali', 'veli', 'gul', 'nur'], dtype='object')

In [61]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [62]:
panser.items

<bound method Series.items of ali     121
veli    200
gul     150
nur      99
dtype: int64>

In [63]:
panser.items()

In [64]:
list(panser.items())

[('ali', 121), ('veli', 200), ('gul', 150), ('nur', 99)]

In [65]:
for index, value in panser.items():
    print(index, "-", value)

ali - 121
veli - 200
gul - 150
nur - 99


In [66]:
"mehmet" in panser

False

In [67]:
"ali" in panser

True

In [68]:
"gulnur" in panser

False

In [69]:
"gul" in panser

True

In [70]:
99 in panser.values

True

In [71]:
500 in panser.values

False

In [72]:
panser["veli"] 

200

In [73]:
panser["veli"] = 571

In [74]:
panser

ali     121
veli    571
gul     150
nur      99
dtype: int64

In [75]:
panser > 130

ali     False
veli     True
gul      True
nur     False
dtype: bool

In [76]:
panser[panser > 130]

veli    571
gul     150
dtype: int64

# The End of the Session - 3

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___