# Matrix Manipulations in Python

## Numpy Arrays and Matrices
In many algorithms, data is represented mathematically as a *vector* or a *matrix*. Conceptually, a vector is just a list of numbers, and a matrix is a two-dimensional list of numbers (a list of lists). This means that in theory, we can perform linear algebra operations using the structures and python methods that we already encountered (lists, arithmetic operations, loops, etc.) However, if we use those stuff, even computing basic operations like matrix multiplication are cumbersome to implement and slow to execute.

We use numpy which implemented more optimized methods for performing basic routines.

In [1]:
import numpy as np 

#### Creating 1-D arrays

In [2]:
# Create a 1-D array by wrapping a list with NumPy's array() function.
a = np.array([1, 4, 3])
a

array([1, 4, 3])

In [3]:
print(a)

[1 4 3]


Notice that the displayed values in the print statement do not contain commas.

#### Creating 2-D arrays

In [4]:
# Create a 2-D array by wrapping a list of lists with NumPy's array() function.
A = np.array([[1, 4, 3],
              [2, 0, 3]])
A

array([[1, 4, 3],
       [2, 0, 3]])

In [5]:
print(A)

[[1 4 3]
 [2 0 3]]


## Basic Operations on Arrays

### Adding, Subtracting, Multiplying, and Dividing a Scalar To An Array

In [6]:
print(a)
print(a + 5)

[1 4 3]
[6 9 8]


In [7]:
# this is also commutative
print(5 + a)

[6 9 8]


In [8]:
# same thing for multiplication
print(a * 5)

[ 5 20 15]


In [9]:
# 
a - 5

array([-4, -1, -2])

In [10]:
a / 5

array([0.2, 0.8, 0.6])

<div class="alert alert-info">
    Note: All arithmetic operations between an array and a scalar applies the operation element-wise on the array.
</div>

### Operations on Arrays with Same Dimensions

In [11]:
a

array([1, 4, 3])

In [12]:
b = np.array([2, 0, 3])

print(a)
print(b)

[1 4 3]
[2 0 3]


In [13]:
a + b

array([3, 4, 6])

In [14]:
a - b

array([-1,  4,  0])

In [15]:
a * b

array([2, 0, 9])

In [16]:
a / b

/var/folders/sd/1vc_q83x5rn9jjrd0x47_cc00000gn/T/ipykernel_66251/1286629031.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([0.5, inf, 1. ])

<div class="alert alert-danger">
    Note: Dividing by zero will give you a warning like the one above. Also, the output shows <b>inf</b> which is the data type used to represent the results when dividing by 0.
</div>

In [17]:
a ** b

array([ 1,  1, 27])

In [18]:
a % b

/var/folders/sd/1vc_q83x5rn9jjrd0x47_cc00000gn/T/ipykernel_66251/2189094906.py:1: RuntimeWarning: divide by zero encountered in remainder
  a % b


array([1, 0, 0])

In [19]:
# Let's set a 2-D array to perform operations
B = np.array([[3, 1, 7],
              [1, 5, 4]])

print('Matrix A:')
print(A)
print()
print('Matrix B:')
print(B)

Matrix A:
[[1 4 3]
 [2 0 3]]

Matrix B:
[[3 1 7]
 [1 5 4]]


In [20]:
A + B

array([[ 4,  5, 10],
       [ 3,  5,  7]])

In [21]:
A - B

array([[-2,  3, -4],
       [ 1, -5, -1]])

In [22]:
A * B

array([[ 3,  4, 21],
       [ 2,  0, 12]])

In [23]:
A / B

array([[0.33333333, 4.        , 0.42857143],
       [2.        , 0.        , 0.75      ]])

In [24]:
A ** B

array([[   1,    4, 2187],
       [   2,    0,   81]])

In [25]:
A % B

array([[1, 0, 3],
       [0, 0, 3]])

Note that both a and A are both `numpy ndarray` types. Think of it as n-dimensional arrays with different values for n.

In [26]:
type(a)

numpy.ndarray

In [27]:
type(A)

numpy.ndarray

### Multiplying Arrays

Matrix multiplication is done using the `.dot()` method

In [28]:
A.dot(a)

array([26, 11])

### Getting The Transpose
for transpose, use the attribute `.T`

In [29]:
A.T

array([[1, 2],
       [4, 0],
       [3, 3]])

### Array Attributes

```Python
dtype  - # The type of the elements in the array
ndim   - # The number of axes (dimensions) of the array
shape  - # A tuple of integers indicating the size of each dimension
size   - # The total numer of elements in the array
```

In [30]:
a.dtype

dtype('int64')

In [31]:
A.dtype

dtype('int64')

In [32]:
a.ndim

1

In [33]:
A.ndim

2

In [34]:
a.shape

(3,)

In [35]:
A.shape

(2, 3)

In [36]:
a.size

3

In [37]:
A.size

6

### Array Creation Routines
Aside from casting other structures such as list as arrays using np.array(), Numpy also have ways to generate commonly used structures.

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
ones = np.ones((4, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
zeros = np.zeros((4, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<div class="alert alert-danger">
    Note: Elements in a numpy array must have a uniform data type (all ints, all floats, etc.).
</div>

In [42]:
# to change data types, you can use the astype() method

In [43]:
I.dtype

dtype('float64')

In [44]:
I.astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

You can also get the **diagonal**, **lower-triangular portion**, and **upper-triangular portion** of a matrix.

In [45]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.triu(ones)

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [47]:
np.tril(ones)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [48]:
np.diag(ones)

array([1., 1., 1., 1.])

<div class="alert alert-success">
    Create the following matrices below without using np.array()
</div>

In [49]:
np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [50]:
np.array([[-2, 3, 3], [-2, -2, 3], [-2, -2, -2]])

array([[-2,  3,  3],
       [-2, -2,  3],
       [-2, -2, -2]])

### Slicing and Indexing Arrays

#### Indexing 1-D arrays
Indexing 1-D arrays is the same syntax as in lists. That is, it follows the following format:

`x[start:stop:step]`

In [51]:
# example
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# access an element by indexing
x[3]

3

In [53]:
# access the first 4 elements
x[0:4]

array([0, 1, 2, 3])

In [54]:
# alternative
x[:4]

array([0, 1, 2, 3])

In [55]:
# getting elements from 3 to 9
x[3:8]

array([3, 4, 5, 6, 7])

#### Indexing 2-D arrays

Correspondingly, for 2D arrays the following are the syntax:

In [56]:
# create a sample 2D array
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
# access the first row
A[0]

array([1, 2, 3, 4])

In [58]:
# access the second row
A[1]

array([5, 6, 7, 8])

In [59]:
# there is no third row
A[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

When we try to get an index which is beyond the dimensions of our array, we get the error above.

In [ ]:
# accessing column 0
A[:, 0]

In [ ]:
# accessing column 1
A[:, 1]

In [ ]:
# accessing element in row 1, column 2
A[1, 2]

In [ ]:
# accessing all rows from column 2 onwards
A[:, 2:]

### Shaping Arrays

You can reshape numpy arrays using the `reshape()` array method.

In [ ]:
A

In [ ]:
A.shape

In [ ]:
# reshape into 1 x 8
A.reshape((1, 8))

In [ ]:
# reshape into 1 x 8
A.reshape((8, 1))

In [ ]:
A.reshape((4, 2))

### Flatten
You can convert a 2-D array into a 1-D array using the `ravel()` method

In [ ]:
A.ravel()

In [ ]:
A.reshape(8)

## Numerical Computing With Numpy

### Universal Functions
A *universal function* is one that operates in the entire array in an element-wise manner.

np.exp() / np.log - # element-wise exponentiation and natural log
np.minimum() / np.maximum() - # element-wise minimum and maximum of two arrays
np.sqrt() - # positive square root element-wise
np.sin(), np.cos(), np.tan(), etc. - # element-wise trigonometric operations

In [ ]:
# calculate the absolute value element-wise
np.abs(A)

In [ ]:
# calculate element-wise exponential
np.exp(A)

In [ ]:
np.log(A)

In [ ]:
np.minimum(np.ones((3, 3)), np.eye(3))

In [ ]:
np.maximum(np.ones((3, 3)), np.eye(3))

In [ ]:
np.sqrt(A)

In [ ]:
# trigonometric functions
np.sin(A)

<div class="alert alert-info">
    Tip: Always use universal numpy functions when working with arrays rather than using the math package.
</div>

### Other Useful Array Methods

In [ ]:
A

In [ ]:
np.all(A > 0)

In [ ]:
np.any(A <= 0)

In [ ]:
A.max()

In [ ]:
A.max(axis=1)

In [ ]:
A.max(axis=0)

In [ ]:
A.min()

In [ ]:
A.min(axis=1)

In [ ]:
A.min(axis=0)

In [ ]:
A.mean()

In [ ]:
A.mean(axis=1)

In [ ]:
A.mean(axis=0)

In [ ]:
A.std()

In [ ]:
A.std(axis=1)

In [ ]:
A.std(axis=0)

### Generating Random Numbers

In [ ]:
# generate random number from standard normal distribution
M_random = np.random.randn(3, 4)
M_random

## Basic Transformations

To demonstrate basic transformations, let's first plot a unit circle which is a matrix represented by a 2 x 200 numpy array s.t. 

$x = \cos(\theta)$,
$y = \sin(\theta)$, and
$\theta \in [0, 2\pi]$

In [ ]:
theta = 2 * np.pi * (np.arange(0, 200) / 200)
x = np.cos(theta)
y = np.sin(theta)

The most basic way of plotting in python is using the `matplotlib` package. The simplest way to create a scatter plot of points is shown below:

In [ ]:
import matplotlib.pyplot as plt # import plotting module

# ensure that your plot stays in the jupyter notebook instead of popping up
%matplotlib inline

In [ ]:
plt.plot(x, y)
plt.axis('equal')

Next, we also need to define basis vectors so we can observe rotations.

In [ ]:
x_b1 = [0, 0]
y_b1 = [0, 1]

x_b2 = [0, 1]
y_b2 = [0, 0]

plt.plot(x_b1, y_b1, color='k')
plt.plot(x_b2, y_b2, color='k')
plt.axis('equal')

In [ ]:
# combining both
def plot(x_circle, y_circle, x_b1, y_b1, x_b2, y_b2):
    plt.plot(x_circle, y_circle)
    plt.plot(x_b1, y_b1, color='k')
    plt.plot(x_b2, y_b2, color='k')
    plt.axis('equal')

In [ ]:
plot(x, y, x_b1, y_b1, x_b2, y_b2)

### Stretch

```Python
np.array([[a, 0],
          [0, b]])
```

In [ ]:
def stretch(A, a, b):
    s = np.array([[a, 0], [0, b]])
    return s.dot(A)

In [ ]:
circle = np.array([x, y])
circle.shape

In [ ]:
basis1 = np.array([x_b1, y_b1])
basis2 = np.array([x_b2, y_b2])

In [ ]:
circle_s = stretch(circle, 3, 2)
basis1_s = stretch(basis1, 3, 2)
basis2_s = stretch(basis2, 3, 2)

In [ ]:
plot(circle_s[0], circle_s[1],
     basis1_s[0], basis1_s[1],
     basis2_s[0], basis2_s[1])

### Shear

Horizontal shear
```Python
np.array([[1, a],
          [0, 1]])
```

Vertical shear
```Python
np.array([[1, 0],
          [b, 1]])
```

In [ ]:
def hshear(A, a):
    s = np.array([[1, a], [0, 1]])
    return s.dot(A)

In [ ]:
circle_h = hshear(circle, 2)
basis1_h = hshear(basis1, 2)
basis2_h = hshear(basis2, 2)

plot(circle_h[0], circle_h[1],
     basis1_h[0], basis1_h[1],
     basis2_h[0], basis2_h[1])

In [ ]:
def vshear(A, b):
    s = np.array([[1, 0], [b, 1]])
    return s.dot(A)

circle_v = vshear(circle, 2)
basis1_v = vshear(basis1, 2)
basis2_v = vshear(basis2, 2)

plot(circle_v[0], circle_v[1],
     basis1_v[0], basis1_v[1],
     basis2_v[0], basis2_v[1])

### Reflection
```Python
(1/(a**2 + b**1)) * np.array([[a**2 - b**2, 2*a*b],
                              [2*a*b, b**2 - a**2]])
```

In [ ]:
def reflection(A, a, b):
    r = (1/(a**2 + b**1)) * np.array([[a**2 - b**2, 2*a*b],
                              [2*a*b, b**2 - a**2]])
    return r.dot(A)

circle_r = reflection(circle, 1, 0)
basis1_r = reflection(basis1, 1, 0)
basis2_r = reflection(basis2, 1, 0)

plot(circle_r[0], circle_r[1],
     basis1_r[0], basis1_r[1],
     basis2_r[0], basis2_r[1])

### Rotation
```Python
np.array([[cos(theta), -sin(theta)],
          [sin(theta), cos(theta)]])
```

In [ ]:
def rotation(A, theta):
    r = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    return r.dot(A)

circle_r = rotation(circle, np.pi / 4)
basis1_r = rotation(basis1, np.pi / 4)
basis2_r = rotation(basis2, np.pi / 4)

plot(circle_r[0], circle_r[1],
     basis1_r[0], basis1_r[1],
     basis2_r[0], basis2_r[1])