In [39]:
import torch
import numpy as np

* Everything in pytorch is based on Tensor operations.
* Tensors are multidimensional arrays of scalars. vectors, matrices, aand tensors themselves.

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([7.0065e-45])
tensor([0.0000e+00, 5.8413e-06, 6.7720e-36])
tensor([[0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
tensor([[[ 0.0000e+00, -2.5244e-29, -3.0864e+03],
         [-2.8629e-42,  9.8091e-45,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


# `torch.rand(size)`  selects random numbers on [0, 1] interval

In [46]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1214, 0.9225, 0.5356],
        [0.0525, 0.4890, 0.6811],
        [0.7607, 0.2002, 0.2133],
        [0.1111, 0.5151, 0.8164],
        [0.5809, 0.1996, 0.5084]])


# Special/Convenient Built in Matrix Templates

### torch.zeros(size), fill with 0
### torch.ones(size), fill with 1
### torch.eye(size), Identity Matrix of Dimension:    $$ \text{size} \cdot \text{size   (dimension of Identity Matrix)}$$

In [11]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
y = torch.ones(3,5)

In [13]:
z = torch.eye(3)

## Check tensor size

In [20]:
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([3, 5]) torch.Size([3, 3])


## Check data type

In [21]:
x.dtype

torch.float32

In [22]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [23]:
# check type
print(x.dtype)

torch.float16


In [24]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [25]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [26]:
# elementwise addition
z = x + y
# torch.add(x,y)

In place addition, everything with a trailing underscore is an inplace operation

i.e. it will modify the variable `y.add_(x)`

## Substraction

In [27]:
z = x - y
z = torch.sub(x, y)

## Multiplication

In [28]:
z = x * y
z = torch.mul(x,y)

## Division

In [29]:
z = x / y
z = torch.div(x,y)

# Slicing

In [30]:
x = torch.rand(5,3)
print(x)

tensor([[0.6080, 0.2258, 0.3429],
        [0.3226, 0.0156, 0.3600],
        [0.6174, 0.0527, 0.7392],
        [0.0096, 0.3552, 0.8920],
        [0.8735, 0.2024, 0.2316]])


In [31]:
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([0.6080, 0.3226, 0.6174, 0.0096, 0.8735])
tensor([0.3226, 0.0156, 0.3600])
tensor(0.0156)


## Get the actual value if only 1 element in your tensor

In [32]:
print(x[1,1].item())

0.015591979026794434


# Reshape with `torch.view()`

In [34]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# Numpy
## Converting a Torch Tensor to a NumPy array and vice versa is very easy


In [35]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


## torch to numpy with `.numpy()`


In [36]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### NOTE: If the Tensor is on the CPU and not the GPU,both objects will share the same memory location, so changing one will also change the other

In [38]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# numpy to torch with
# `.from_numpy(x)`


In [40]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### BE CAREFUL when modifying below!

In [41]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## by default all tensors are created on the CPU, but you can also move them to the `GPU `(only if it's available )

In [42]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings '.to("cuda")'
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # '.to'  can also change dtype together!

In [43]:
z = z.numpy()

In [44]:
z

array([[ 0.2596848 ,  1.1230211 ,  0.54667455,  0.96422154,  0.18915969,
         1.0448366 ,  0.50658983,  0.5532421 ],
       [-0.9476617 ,  0.0901087 ,  0.41670004,  1.2089915 , -1.0845256 ,
        -1.7596781 , -0.8572808 , -0.24197435]], dtype=float32)