<p style="color: yellow; background-color: blue; text-align: center; font-weight: bold; font-size:36px; line-height:40px">Les bases de Python</p>

<p style="color: blue; text-align: left; font-weight: bold;font-size:30px; line-height:15px">Les Fonctions</p>

In [3]:
f = lambda x , y : x**2 + 2*x*y + y**2

In [4]:
print(f(3,5))

64


In [5]:
def e_potentielle(masse, hauteur, g):
    E = masse * hauteur *g
    print(E, "joules")
    return E

In [6]:
resultat = e_potentielle(3,2,9.81)

58.86 joules


In [7]:
def e_potentielle(masse, hauteur,e_limite, g):
    E = masse * hauteur *g
    if E >= e_limite:
        print('supérieur')
    else:
        print('inférieur')
            
    return E

In [8]:
e_potentielle(5,3,156,9)

inférieur


135

In [9]:
def fibonacci(n):
    #return lz suite de fibonacci jusqu'à n
    a = 0
    b = 1
    while a< n :
        print(a)
        a,b = b, a+b

In [10]:
fibonacci(100)

0
1
1
2
3
5
8
13
21
34
55
89


In [11]:
n = 12
x = 0
y = 1
while x<n:
    print(x)
    x,y = y, x+y
    
    

0
1
1
2
3
5
8


<p style="color: blue; text-align: left; font-weight: bold;font-size:30px; line-height:15px">Les listes</p>

In [12]:
prenom = 'Fatima'
print(prenom[:3])

Fat


In [13]:
villes = ['Paris', 'Berlin', 'Tokyo','Rio']
villes.append('Oslo')

In [14]:
villes

['Paris', 'Berlin', 'Tokyo', 'Rio', 'Oslo']

In [15]:
villes.insert(3,'Denver')

In [16]:
villes


['Paris', 'Berlin', 'Tokyo', 'Denver', 'Rio', 'Oslo']

In [17]:
villes_2= ['Nairobi','Stokholm']

In [18]:
villes.extend(villes_2)

In [19]:
villes


['Paris', 'Berlin', 'Tokyo', 'Denver', 'Rio', 'Oslo', 'Nairobi', 'Stokholm']

In [20]:
len(villes)

8

In [21]:
#trier par ordre alphabetique
villes.sort()

In [22]:
villes

['Berlin', 'Denver', 'Nairobi', 'Oslo', 'Paris', 'Rio', 'Stokholm', 'Tokyo']

In [23]:
villes.sort(reverse=True)

In [24]:
villes

['Tokyo', 'Stokholm', 'Rio', 'Paris', 'Oslo', 'Nairobi', 'Denver', 'Berlin']

In [25]:
liste_2= [2,45,56,3,78,12,34]
liste_2.sort()

In [26]:
liste_2

[2, 3, 12, 34, 45, 56, 78]

In [27]:
#le nombre de fois qu'u element apparait dans ma liste
villes.count('Paris')

1

In [28]:
#verifier 
if 'Paris' in villes:
    print('oui')
else:
    print('non')

oui


In [29]:
for i in villes:
    print(i)

Tokyo
Stokholm
Rio
Paris
Oslo
Nairobi
Denver
Berlin


In [30]:
#enumerate fait passer deux choses : l'index et le contenu
for index, valeur in enumerate(villes):
    print(index,valeur)

0 Tokyo
1 Stokholm
2 Rio
3 Paris
4 Oslo
5 Nairobi
6 Denver
7 Berlin


In [31]:
#commande Zip permet de mixer deux listes ensemble:
for a , b in zip(villes, liste_2):
    print(a,b)

Tokyo 2
Stokholm 3
Rio 12
Paris 34
Oslo 45
Nairobi 56
Denver 78


In [32]:
def fibonacci_list(n):
    #return lz suite de fibonacci jusqu'à n
    a = 0
    b = 1
    liste_fib =[]
    while a< n :
        liste_fib.append(a)
        a,b = b, a+b
    print(liste_fib)

In [33]:
fibonacci_list(100)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


<p style="color: blue; text-align: left; font-weight: bold;font-size:30px; line-height:15px">Les Dictionnaires</p>

In [34]:
traduction = {
    "chien":"dog",
    "chat": "cat",
    "souris":"mouse",
    "oiseau":"bird"
}



In [35]:
inventaire = {
    "bananes": 5000,
    "pommes": 3000,
    "ananas":1000
}

In [36]:
dictionnaire_3 = {
    "dict_1": traduction,
    "dict_2":inventaire
}

In [37]:
inventaire.values()

dict_values([5000, 3000, 1000])

In [38]:
inventaire.keys()

dict_keys(['bananes', 'pommes', 'ananas'])

In [39]:
len(inventaire)

3

In [40]:
inventaire["abricots"] = 6578

In [41]:
inventaire

{'bananes': 5000, 'pommes': 3000, 'ananas': 1000, 'abricots': 6578}

In [42]:
#permet de retrouver quelque chose et sinon d'afficher une valeur par défault
inventaire.get('peches',"ya pas")


'ya pas'

In [43]:
inventaire.get('pommes','ya pas')

3000

In [44]:
#mthod from keys : ajouter une liste au dictionnaire
liste_1= ('Paris','Londres','Marseille')

In [45]:
inventaire = inventaire.fromkeys(liste_1, 'defaut')

In [46]:
inventaire

{'Paris': 'defaut', 'Londres': 'defaut', 'Marseille': 'defaut'}

In [47]:
#enlever un des elts
bananes = inventaire.pop("Londres")

In [48]:
inventaire

{'Paris': 'defaut', 'Marseille': 'defaut'}

In [49]:
#pour afficher juste les clés
for i in inventaire :
    print (i) 

Paris
Marseille


In [50]:
#pour afficher juste les valeurs
for i in inventaire.values() :
    print (i) 

defaut
defaut


In [51]:
#pour afficher les valeurs et les clés
for k , v in inventaire.items() :
    print (k , v) 

Paris defaut
Marseille defaut


In [52]:
classeur = {
    "positif": [],
    "negatif":[]
}

In [53]:
def trier(classeur, nombre):
    if nombre >0:
        classeur["positif"].append(nombre)
    else:
        classeur["negatif"].append(nombre)
    return classeur
    

In [54]:
classeur

{'positif': [], 'negatif': []}

In [55]:
trier(classeur, 5)

{'positif': [5], 'negatif': []}

<p style="color: blue; text-align: left; font-weight: bold;font-size:30px; line-height:15px">Les list comprehension</p>

In [56]:
liste_1 = []
for i in range(10):
    liste_1.append(i**2)
print(liste_1)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [57]:
liste_2 = [i**2 for i in range(10)]
print(liste_2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [58]:
#nested lists
liste_3 = [[i for i in range(5)] for j in range (3)]
liste_3

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

<p style="color: blue; text-align: left; font-weight: bold;font-size:30px; line-height:15px">Les Dict comprehension</p>

In [59]:
prenoms = ['Pierre', 'Guillaume', 'Fatima', 'Awa']

In [60]:
dico = {k:v for k,v in enumerate(prenoms)}
print(dico)

{0: 'Pierre', 1: 'Guillaume', 2: 'Fatima', 3: 'Awa'}


In [61]:
dico.keys()

dict_keys([0, 1, 2, 3])

In [62]:
dico.values()

dict_values(['Pierre', 'Guillaume', 'Fatima', 'Awa'])

In [63]:
ages = [24, 30, 38, 35]

In [64]:
dico_2 = {prenom: age for prenom, age in zip(prenoms, ages)if age > 30}
dico_2

{'Fatima': 38, 'Awa': 35}

<p style="color: blue; text-align: left; font-weight: bold;font-size:30px; line-height:15px">Les Tuple comprehension</p>

In [65]:
tuple_1 = tuple((i**2 for i in range(10)))
tuple_1

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)

In [66]:
# dictionnaire k:v
# k = 0 à 20
# v = k **2
liste_d= [i for i in range (20)]
print(liste_d)
liste_e =[i**2 for i in range (20)]
print(liste_e)
dico_3 = {k:v for k, v in zip (liste_d, liste_e)}
print(dico_3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}


In [67]:
#autre methode
carres_pairs= {
   str(k) : k**2 for k in range(0,20)
}

In [68]:
print(carres_pairs)

{'0': 0, '1': 1, '2': 4, '3': 9, '4': 16, '5': 25, '6': 36, '7': 49, '8': 64, '9': 81, '10': 100, '11': 121, '12': 144, '13': 169, '14': 196, '15': 225, '16': 256, '17': 289, '18': 324, '19': 361}


## Built in Functions

In [69]:
liste_F= [3,4,-6,67,0]
min(liste_F)

-6

In [70]:
max(liste_F)

67

In [71]:
len(liste_F)

5

In [72]:
sum(liste_F)

68

In [73]:
any(liste_F)

True

In [74]:
all(liste_F)

False

## Conversion

In [75]:
x = 10
type(x)

int

In [76]:
x = str(x)

In [77]:
type(x)

str

In [78]:
y = '20'
y= int(y)

In [79]:
x = 10
float(x)

10.0

In [80]:
 tuple_F =tuple(liste_F)

In [81]:
list(tuple_F)

[3, 4, -6, 67, 0]

In [82]:
bin(15)

'0b1111'

In [83]:
oct(15)

'0o17'

In [84]:
## format
x = 25
ville = 'Paris'
message = "la température est de {} degrésC à {}".format(x, ville)
print(message)

la température est de 25 degrésC à Paris


In [85]:
import numpy as np
parametres = {
    "W1": np.random.randn(2,4),
    "b1": np.zeros((2,1)),
    "W2": np.random.randn(2,2),
    "b2":np.zeros((2,1))
}

In [86]:
for i in range(1,3):
    print('couche',i)
    print(parametres['W{}'.format(i)])

couche 1
[[ 0.18084931 -0.73294944  0.37963245 -0.51682132]
 [ 0.65983073 -0.66306372 -0.52575362  0.19734399]]
couche 2
[[0.43076086 0.38727648]
 [1.32495825 2.90844254]]


## Open files

In [87]:
f = open('fichier.txt','w')

In [88]:
f.write('bonjour')
f.close()

In [89]:
f = open('fichier.txt','r')
print(f.read())
f.close

bonjour


<function TextIOWrapper.close()>

In [90]:
#on utilise la boucle with open pour faire tout ce qu'il faut faire 
with open('fichier.txt', 'w') as f:
    for i in range(10):
        f.write("{}^2 = {}\n".format(i, i**2))

In [91]:
#ouvrir tous les elements de mon fichier et les mettre dans une liste 
with open ('fichier.txt', 'r') as f :
           listf= f.readlines()
listf
                

['0^2 = 0\n',
 '1^2 = 1\n',
 '2^2 = 4\n',
 '3^2 = 9\n',
 '4^2 = 16\n',
 '5^2 = 25\n',
 '6^2 = 36\n',
 '7^2 = 49\n',
 '8^2 = 64\n',
 '9^2 = 81\n']

In [92]:
#pour enlever le \n
with open ('fichier.txt','r') as f:
    listf= f.read().splitlines()
listf

['0^2 = 0',
 '1^2 = 1',
 '2^2 = 4',
 '3^2 = 9',
 '4^2 = 16',
 '5^2 = 25',
 '6^2 = 36',
 '7^2 = 49',
 '8^2 = 64',
 '9^2 = 81']

In [93]:
#avec une liste comprehension
listf = [lines.strip() for lines in open('fichier.txt','r')]
listf

['0^2 = 0',
 '1^2 = 1',
 '2^2 = 4',
 '3^2 = 9',
 '4^2 = 16',
 '5^2 = 25',
 '6^2 = 36',
 '7^2 = 49',
 '8^2 = 64',
 '9^2 = 81']

<p style="color: blue; text-align: left; font-weight: bold; font-size:25px; line-height:20px">Modules et packages</p>


In [94]:
import random

In [95]:
random.seed(0)
print(random.choice(['jean','marc','julie']))

marc


In [96]:
random.seed(3)
random.random()#float
random.randint(3,67)#int
random.randrange(100)#int entre 0 et 100
random.sample(range(100),10)#list entre 0 et 100 de 10 chiffres
random.sample(range(100), random.randrange(10))#list entre 0 et 100 nombre de chiffres aletaoiree123
liste123 = [3,56,78,9,4,6,8,3]
allo = random.shuffle(liste123)

In [97]:
print(liste123)

[56, 6, 3, 3, 9, 4, 8, 78]


In [98]:
import os

In [99]:
os.getcwd() #savoir ou on se situe dans le répertoire

'C:\\Users\\TURBULANCE\\PYTHON_CLSM\\01_DIFFERENT\\01\\python_base_FatimaMoqran\\python_base-master'

In [100]:
import glob

In [101]:
glob.glob('*')#connaitre tous les fichiers de mon répertoire

['fichier.txt',
 'python_basics-Copy1.ipynb',
 'python_basics.ipynb',
 'README.md']

In [102]:
filesnames = glob.glob("*.txt")

In [103]:
for file in filesnames:
    with open(file,'r') as f:
        print(f.read())

0^2 = 0
1^2 = 1
2^2 = 4
3^2 = 9
4^2 = 16
5^2 = 25
6^2 = 36
7^2 = 49
8^2 = 64
9^2 = 81



### petit programme utile 

In [104]:
#utiliser cette technique : enregistrer dans une varaiables tout le contenu qui nous viens de fichierer s
#pour chaque fichier enregistrer le contenu dans nos variables
d={}
for file in filesnames:
    with open(file,'r') as f:
        d[file] = f.read().splitlines()

In [105]:
print(d)

{'fichier.txt': ['0^2 = 0', '1^2 = 1', '2^2 = 4', '3^2 = 9', '4^2 = 16', '5^2 = 25', '6^2 = 36', '7^2 = 49', '8^2 = 64', '9^2 = 81']}
