In [87]:
%pylab inline
import numpy as np
import math

Populating the interactive namespace from numpy and matplotlib


### Defining a joint distribution over two discrete random variables
The probabilities are organized in a 2D array, where the columns correspond to values of $x$ and the rows correspond to values of $y$

In [88]:
def ComputeStatistics(P,x,y):
    P/=np.sum(P) # normalize the disttribution
    Px=np.sum(P,axis=0) # compute marginals
    Py=np.sum(P,axis=1)
    Ex=np.dot(Px,x)
    Ey=np.dot(Py,y)
    Ex2=np.dot(Px,x**2)
    Ey2=np.dot(Py,y**2)
    stdx=math.sqrt(Ex2-Ex**2)
    stdy=math.sqrt(Ey2-Ey**2)
    
    nx=x-Ex
    ny=y-Ey
    
    cov=np.dot(P.flatten(), np.outer(ny,nx).flatten())
    corr=cov/(stdx*stdy)
    return {
        'P':P,
        'x':x,
        'y':y,
        'Px':Px,
        'Py':Py,
        'Ex':Ex,
        'Ey':Ey,
        'stdx':stdx,
        'stdy':stdy,
        'cov':cov,
        'corr':corr
    }


In [54]:
#### We start with positive weights that don't sum to 1
P=np.array([[2.,2,4],[1,1,2]])
P2=copy(P)
P

array([[2., 2., 4.],
       [1., 1., 2.]])

In [55]:
# We then normalize the weights
# using Pure Python

#Compute the sum
s=0
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        s+=P[i,j]
print(f"Sum = {s}")
#divide by the sum
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        P[i,j] /= s
print(P)

Sum = 12.0
[[0.16666667 0.16666667 0.33333333]
 [0.08333333 0.08333333 0.16666667]]


In [56]:
# Using Numpy we can write it in a much shorter way
P2/=sum(P2)
P2

array([[0.16666667, 0.16666667, 0.33333333],
       [0.08333333, 0.08333333, 0.16666667]])

In [57]:
# The values that the random variables x and y take
x=np.array([1,2,6])
y=np.array([-1,1])

In [58]:
shape(P)

(2, 3)

#### Computing Marginals
The marginal distributions are the probabilities associated with each random variable alone.

In [59]:
Px=[0.]*shape(P)[1]
Py=[0.]*shape(P)[0]

for i in range(len(Px)):
    for j in range(len(Py)):
        Px[i]+=P[j,i]
        Py[j]+=P[j,i]
Px,Py

([0.25, 0.25, 0.5], [0.6666666666666666, 0.3333333333333333])

In [60]:
#the numpy way:
Px=sum(P,axis=0)
Py=sum(P,axis=1)
Px,Py

(array([0.25, 0.25, 0.5 ]), array([0.66666667, 0.33333333]))

### Check whether $x$ and $y$ are independent

If they are independent then the outer product and P should be equal.

In [61]:
# The pure python way
for i in range(len(Px)):
    for j in range(len(Py)):
        if Px[i]*Py[j] != P[j,i]:
            print("Px[%d]*Py[%d] != P[%d,%d] ::::: %5.3f*%5.3f = %5.3f != %5.3f"%\
                    (i,j,j,i,Px[i],Py[j],Px[i]*Py[j],P[j,i]))


In [62]:
# The numpy way
np.outer(Px,Py).T - P

array([[0., 0., 0.],
       [0., 0., 0.]])

### Computing the covariance

### Calculating the mean and standard deviation
To calculate the mean of $X$ and $Y$ under this distribtion in python, we need to iterate through the values of $x$ and $y$ and plug them into the formuls $E[X] = \sum_x P(X=x)x$. Similarly for standard deviation.


In [63]:
from math import sqrt
#The python way
Ex = 0
for i in range(3):
    Ex+=Px[i]*x[i]
Ey = 0
for i in range(2):
    Ey+=Py[i]*y[i]

varx = 0
for i in range(3):
    varx+=Px[i]*(x[i] - Ex)**2
stdx = sqrt(varx)

vary = 0
for i in range(2):
    vary+=Py[i]*(y[i] - Ey)**2
stdy = sqrt(vary)

Ex,Ey,stdx,stdy

(3.75, -0.3333333333333333, 2.277608394786075, 0.9428090415820634)

In [64]:
# In numpy you can use np.dot(A,B) which calculates the pairwise product of elements in A and B and sums them up
Ex=np.dot(Px,x)
Ey=np.dot(Py,y)
Ex2=np.dot(Px,x**2)
Ey2=np.dot(Py,y**2)
stdx=sqrt(Ex2-Ex**2)
stdy=sqrt(Ey2-Ey**2)
print('Ex=%f,Ey=%f,stdx=%f,stdy=%f'%(Ex,Ey,stdx,stdy))

Ex=3.750000,Ey=-0.333333,stdx=2.277608,stdy=0.942809


#### Subtract the means

In [65]:
nx=x-Ex
nx

array([-2.75, -1.75,  2.25])

In [66]:
ny=y-Ey
ny

array([-0.66666667,  1.33333333])

### Calculate the covariance


In [67]:
s=0
for i in range(len(x)):
    for j in range(len(y)):
        s+=P[j,i]*nx[i]*ny[j]
print(f'the covariance is {s}')#our expected values are now 0 so nothing to subtract)

the covariance is 1.1102230246251565e-16


In [68]:
# numpy
print('the covariance is', np.dot(P.flatten(), np.outer(ny,nx).flatten()))

the covariance is 5.551115123125783e-17


### and the correlation


In [69]:
s/(stdx*stdy),stdx,stdy

(5.170201105284541e-17, 2.277608394786075, 0.9428090415820634)

In [73]:

x=np.arange(1.,2.,0.2)
y=np.arange(0.,1.,0.2)
P=np.eye(5)
print(x,"\t",y,"\n\n",P)


[1.  1.2 1.4 1.6 1.8] 	 [0.  0.2 0.4 0.6 0.8] 

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [75]:
A=ComputeStatistics(P,x,y)
print( A['cov'],A['corr'])

0.07999999999999999 0.9999999999999981


## Empirical statistics

If we now draw samples from these distributions, we can see that the emperical statistics, the population mean, population standard deviation and population covariance approach the original values of mean, standard deviation and covariance.

In [76]:
P=np.array([[1.,1,1],[1,1,2],[2,1,1]])
x=np.array([-1,0,1]); y=np.array([-1,0,1])
A=ComputeStatistics(P,x,y)
Px=A['Px']
Px,A['Ex'],A['cov']

(array([0.36363636, 0.27272727, 0.36363636]), 0.0, -0.09090909090909091)

In [77]:
Px

array([0.36363636, 0.27272727, 0.36363636])

In [78]:
np.random.choice(x,100,True, Px)

array([ 0,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  0, -1,  0,  1,
        1,  0,  1, -1, -1,  1, -1,  1,  1, -1,  0,  0,  1,  0, -1, -1,  0,
        0,  1,  0,  1,  1,  1,  1, -1, -1, -1,  0,  0,  0, -1,  1,  1,  1,
        1,  0,  1,  0,  0,  1,  1, -1,  0, -1, -1,  1, -1,  1,  1, -1, -1,
       -1,  0, -1, -1,  1, -1,  1,  1, -1, -1,  0,  1, -1,  1,  1, -1,  1,
       -1, -1,  1,  0, -1,  1, -1,  0, -1,  1,  1, -1, -1,  0,  1])

In [80]:
numsamples = [2,10,100,100000]

for num in numsamples: 
    print (f"Sample mean after drawing {num} samples = {np.mean(np.random.choice(x, num, True, Px))}")
    

Sample mean after drawing 2 samples = 1.0
Sample mean after drawing 10 samples = 0.8
Sample mean after drawing 100 samples = 0.02
Sample mean after drawing 100000 samples = 0.00105


In [82]:
#To calculate the covariance, we will generate samples (x,y) form the joint distribution P possible samples
xy =  np.array([(i,j) for i in x for j in y])
I=np.random.choice(xy.shape[0], num, True, P.T.flatten())
xy[I][:20]

array([[ 1,  0],
       [ 0,  1],
       [ 1,  0],
       [-1,  1],
       [ 0, -1],
       [ 1,  1],
       [-1,  0],
       [ 0,  1],
       [ 0, -1],
       [ 1,  0],
       [-1,  0],
       [-1,  1],
       [ 0,  1],
       [-1,  1],
       [ 1,  0],
       [-1,  0],
       [-1,  1],
       [-1,  0],
       [-1, -1],
       [ 0, -1]])

In [83]:
xy.shape

(9, 2)

In [86]:
for num in numsamples:
    samples = np.random.choice(xy.shape[0], num, True, P.T.flatten()), #choose rows
    print (f"Population covariance after drawing {num} samples = {np.cov(xy[samples][:,0], xy[samples][:,1])[0,1]}")

Population covariance after drawing 2 samples = -2.0
Population covariance after drawing 10 samples = 0.3333333333333333
Population covariance after drawing 100 samples = -0.22525252525252523
Population covariance after drawing 100000 samples = -0.09365174091740924
