In [1]:
import numpy as np

In [2]:
un_panda_numpy = np.array([100,5,20,80])
un_panda_numpy

array([100,   5,  20,  80])

In [3]:
#if have more pandas...
#I create a list of np.array
panda_family =[
    np.array([100, 5 , 20, 80]), #maman panda
    np.array([50, 2.5, 10, 40]), #bebe panda
    np.array([110, 6, 22, 80]), #papa panda
]

panda_family_numpy = np.array(panda_family)

panda_family_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [4]:
panda_family_numpy[2,0] #size of papa's panda patte numpy's style

110.0

In [5]:
panda_family_numpy[:,0]

array([100.,  50., 110.])

In [6]:
import pandas as pd
#I create a DataFrame , I  
panda_family_df = pd.DataFrame(panda_family)
panda_family_df

0    1     2     3
0  100.0  5.0  20.0  80.0
1   50.0  2.5  10.0  40.0
2  110.0  6.0  22.0  80.0

In [7]:
panda_family_df = pd.DataFrame(panda_family_numpy,
                              index = ['maman','bebe','papa'],
                              columns = ['pattes', 'poil','queue','ventre'])
panda_family_df

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0

Index can be a sting or an integer.
By default it is an integer from 0.


#  DataFrames fonctionalities

In [8]:
panda_family_df.ventre

maman    80.0
bebe     40.0
papa     80.0
Name: ventre, dtype: float64

In [9]:
panda_family_df["ventre"]

maman    80.0
bebe     40.0
papa     80.0
Name: ventre, dtype: float64

In [10]:
for ind_ligne, contenu_ligne in panda_family_df.iterrows():
    print ("Voici le panda %s:"% ind_ligne)
    print(contenu_ligne)
    print("-------------------------------")

Voici le panda maman:
pattes    100.0
poil        5.0
queue      20.0
ventre     80.0
Name: maman, dtype: float64
-------------------------------
Voici le panda bebe:
pattes    50.0
poil       2.5
queue     10.0
ventre    40.0
Name: bebe, dtype: float64
-------------------------------
Voici le panda papa:
pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64
-------------------------------


In [11]:
panda_family_df.iloc[2] #with iloc(),indexation positionelle
panda_family_df.loc["papa"] # with loc(), indexation by label

pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [12]:
#we want all tne pandas with the bottom size is 80
panda_family_df["ventre"]==80

maman     True
bebe     False
papa      True
Name: ventre, dtype: bool

We test each element of the column "ventre"

In [13]:
#we want to select only pandas with the bottom is 80 size
masque = panda_family_df["ventre"]== 80
pandas_80 = panda_family_df[masque]

pandas_80

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
papa    110.0   6.0   22.0    80.0

In [14]:
#pour selectionner les pandas qui n'ont pas un ventre de 80cm
panda_family_df[~masque]


pattes  poil  queue  ventre
bebe    50.0   2.5   10.0    40.0

In [15]:
#assembler ensemble deux dataFrame

quelques_pandas = pd.DataFrame([[105,4,19,80],[100,5,20,80]],
                               #2 nouveaux pandas
                              columns = panda_family_df.columns )
                            # même colonnes que famille_panda_dff
    
tous_les_pandas = panda_family_df.append(quelques_pandas)
tous_les_pandas

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0
1       100.0   5.0   20.0    80.0

In [16]:
# pour dedoublonner les doublons
tous_les_pandas.drop_duplicates()

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0

In [17]:
# on peut l'enregistrer dans une nouvelle variable
pandas_uniques = tous_les_pandas.drop_duplicates()

#ou remplacerla variable tous_les_pandas par le nouveau data frame dedoublonné
tous_les_pandas = tous_les_pandas.drop_duplicates()

In [18]:
#accéder aux noms des colonnes
panda_family_df.columns

Index(['pattes', 'poil', 'queue', 'ventre'], dtype='object')

In [19]:
 #une nouvelle colonne, composée de chaines de caractères
panda_family_df["sexe"] = ["f", "f","m"]

In [20]:
#obtenir le nombre de lignes
len(panda_family_df)

3

In [21]:
#obtenir les valeurs distinctes d'une colonne:
panda_family_df.ventre.unique()

array([80., 40.])

Lire un Fichier CSV avec Pandas

In [24]:
#data = pd.read_csv("data.csv",sep=";")