# 100 NUMPY EXERCICES



#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/TURBULENCE/anaconda3\\Library\\include']


#### 3. Create a null vector of size 15 (★☆☆)

In [4]:
K = np.zeros(15)
print(K)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
K = np.zeros((10,10))
print("%d bytes" % (K.size * K.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 15 but the sixth value which is 6 (★☆☆)

In [6]:
K = np.zeros(15)
K[5] = 6
print(K)

[0. 0. 0. 0. 0. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 60 (★☆☆)

In [7]:
K = np.arange(20,61)
print(K)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
K = np.arange(20,61)[::-1]
print(K)

[60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37
 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. Create a 3x3 matrix with values ranging from 10 to 18 (★☆☆)

In [9]:
K= np.arange(10,19).reshape(3, 3)
print(K)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 4x4 identity matrix (★☆☆)

In [11]:
K = np.eye(4)
print(K)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 4x4x4x4 array with random values (★☆☆)

In [12]:
K = np.random.random((4,4,4,4))
print(K)

[[[[0.58252847 0.4045524  0.26121182 0.3715277 ]
   [0.5948814  0.59739685 0.05164025 0.66076057]
   [0.57879329 0.56510123 0.47584225 0.81069742]
   [0.91427717 0.4209525  0.05193513 0.9525269 ]]

  [[0.5602574  0.74301167 0.01143379 0.46314256]
   [0.45745892 0.14232016 0.94954764 0.64501688]
   [0.44531953 0.29293785 0.92213884 0.85149955]
   [0.78610663 0.00403914 0.79873517 0.45991185]]

  [[0.39908633 0.89644842 0.84146248 0.54016357]
   [0.37513175 0.22061165 0.40875864 0.88451155]
   [0.58860275 0.16341877 0.79542385 0.21804063]
   [0.69974854 0.87232398 0.61293919 0.92930239]]

  [[0.76922184 0.22364459 0.06239937 0.11739918]
   [0.5955437  0.36532749 0.12376177 0.28169642]
   [0.13611832 0.23630807 0.55351959 0.30769386]
   [0.64708944 0.98673764 0.10688912 0.5396103 ]]]


 [[[0.56215006 0.09905027 0.24517031 0.22200976]
   [0.26043313 0.56004362 0.05744849 0.49198901]
   [0.40333668 0.08863733 0.10212895 0.75708749]
   [0.64046588 0.53866728 0.4028514  0.0889493 ]]

  [[0.50

#### 13. Create a 8x8 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
K = np.random.random((8,8))
print(K)
print()
Kmin, Kmax = K.min(), K.max()
print(K.min(), K.max())

[[0.07099128 0.04495415 0.21092979 0.10430545 0.52474028 0.75595621
  0.39638571 0.50090654]
 [0.94290001 0.7907999  0.04928541 0.74763439 0.94834863 0.408019
  0.3314672  0.95968188]
 [0.58737457 0.87376653 0.02978218 0.19029135 0.94057223 0.25419656
  0.48618975 0.3083686 ]
 [0.68454128 0.50677717 0.04231497 0.22728374 0.07926898 0.75805074
  0.61885097 0.38670181]
 [0.19374188 0.53541846 0.09318652 0.6615998  0.95532347 0.65035146
  0.71634194 0.08858755]
 [0.96872297 0.36490059 0.64162091 0.74634806 0.03189579 0.20124053
  0.40640469 0.40374137]
 [0.90001089 0.64403806 0.75800078 0.1128812  0.6907184  0.6585901
  0.09631075 0.21164241]
 [0.4093521  0.00289689 0.44443804 0.65993655 0.48274639 0.88269527
  0.54239764 0.41010756]]

0.0028968937490264635 0.9687229687877538


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
K = np.random.random(20)
print(K)
print()

m = K.mean()
print(m)

[0.92015596 0.87689647 0.52333859 0.49730648 0.693062   0.9175828
 0.02502669 0.18803986 0.93459097 0.37372462 0.67062588 0.78866517
 0.42708567 0.76573951 0.42102658 0.82814319 0.46912586 0.37634886
 0.47610727 0.24723172]

0.5709912071620485


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
K = np.ones((10,10))
print(K)
print()

K[1:-1,1:-1]=0
print(K)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
K = np.ones((5,5))
K = np.pad(K, pad_width=1, mode='constant', constant_values=0)
print(K)
print()

# Using fancy indexing
K[:, [0, -1]] = 0
K[[0, -1], :] = 0
print(K)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
K = np.diag(1 + np.arange(4), k=-1)
print(K)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
K = np.zeros((8,8), dtype=int)
print(K)
print()

K[1::2,::2]=1
print(K)
print()

K[::2,1::2]=1
print(K)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
K = np.unravel_index(99,(6,7,8))
print(K)

(1, 5, 3)


#### 21. Create a checkerboard 6x6 matrix using the tile function (★☆☆)

In [21]:
K = np.tile(np.array([[0,1],[1,0]]),(3,3))
print(K)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
K = np.random.random((5,5))
K = (K - np.mean (K)) / (np.std (K))
print(K)

[[ 0.63918086 -0.94329848 -1.47280899 -0.42455847  0.19892748]
 [ 0.0703864  -1.09594283 -1.41073791 -0.01830372  0.22902575]
 [-0.44597893 -0.61677376 -1.75311294  0.72429475 -1.25501525]
 [-0.54194021  1.59270641  1.05899047  0.10595266  1.94674573]
 [ 1.17568852 -0.14623826  1.34531819 -0.11632495  1.15381747]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\TURBULENCE\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
K = np.dot(np.ones((5,3)), np.ones((3,2)))
print(K)

print()

# Alternative solution, in Python 3.5 and above
K = np.ones((5,3)) @ np.ones((3,2))
print(K)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 2 and 9, in place. (★☆☆)

In [25]:
K = np.arange(11)
K[(2 < K) & (K < 9)] *= -1
print(K)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\TURBULENCE\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\TURBULENCE\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
K = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(K)), K))

print()

# More readable but less efficient
print(np.where(K>0, np.ceil(K), np.floor(K)))

[  2.   5. -10.  -1.  -3.   1.  -4.   6.   7.  -2.]

[  2.   5. -10.  -1.  -3.   1.  -4.   6.   7.  -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
K1 = np.random.randint(0,5,20)
K2 = np.random.randint(0,5,20)
print(np.intersect1d(K1,K2))

[0 1 2 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\TURBULENCE\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print("Yesterday:",yesterday)
print("Today:",today)
print("Tomorrow:",tomorrow)

Yesterday: 2021-01-10
Today: 2021-01-11
Tomorrow: 2021-01-12


#### 34. How to get all the dates corresponding to the month of Jun 2019? (★★☆)

In [33]:
K = np.arange('2019-06', '2019-07', dtype='datetime64[D]')
print(K)

['2019-06-01' '2019-06-02' '2019-06-03' '2019-06-04' '2019-06-05'
 '2019-06-06' '2019-06-07' '2019-06-08' '2019-06-09' '2019-06-10'
 '2019-06-11' '2019-06-12' '2019-06-13' '2019-06-14' '2019-06-15'
 '2019-06-16' '2019-06-17' '2019-06-18' '2019-06-19' '2019-06-20'
 '2019-06-21' '2019-06-22' '2019-06-23' '2019-06-24' '2019-06-25'
 '2019-06-26' '2019-06-27' '2019-06-28' '2019-06-29' '2019-06-30']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
K = np.random.uniform(0,10,10)

print(K - K%1)
print(K // 1)
print(np.floor(K))
print(Z.astype(int))
print(np.trunc(K))

[9. 6. 2. 5. 5. 3. 4. 9. 5. 3.]
[9. 6. 2. 5. 5. 3. 4. 9. 5. 3.]
[9. 6. 2. 5. 5. 3. 4. 9. 5. 3.]
[-2147483648]
[9. 6. 2. 5. 5. 3. 4. 9. 5. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
K = np.zeros((5,5))
K += np.arange(5)
print(K)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
def generate():
    for x in range(10):
        yield x
K = np.fromiter(generate(),dtype=float,count=-1)
print(K)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
K = np.linspace(0,1,11,endpoint=False)[1:]
print(K)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
K = np.random.random(10)
K.sort()
print(K)

[0.09855932 0.26132607 0.28802039 0.35716658 0.36567869 0.50630271
 0.5322355  0.58715093 0.72568987 0.83481199]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [40]:
K = np.arange(20)
np.add.reduce(K)

190

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [41]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [42]:
K = np.zeros(10)
K.flags.writeable = False
#K[0] = 1
#print(K)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [122]:
K = np.random.random((10,2))
A, B = K[:,0], K[:,1]
M = np.sqrt(A**2 + B**2)
N = np.arctan2(B, A)
print(M)
print(N)

[1.25236978 0.53439665 0.9920486  0.90484244 0.47314029 0.81610952
 0.17332153 0.46923145 0.56071723 0.38573422]
[0.79891358 0.73149753 0.17050094 1.10269579 1.0304205  0.6871006
 0.54589527 0.82478657 0.55113586 1.02745029]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [44]:
K = np.random.random(10)
K[K.argmax()] = 0
print(K)

[0.29594928 0.282571   0.29402165 0.         0.13022648 0.73031897
 0.68052999 0.55743689 0.64391982 0.46027929]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [45]:
K = np.zeros((5,5), [('x',float),('y',float)])
K['x'], K['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(K)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [46]:
A = np.arange(10)
B = A + 0.5
C = 1.0 / np.subtract.outer(A, B)
print(np.linalg.det(C))

33961.93294480225


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [47]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [48]:
np.set_printoptions(threshold=float("inf"))
K = np.zeros((16,16))
print(K)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [123]:
K = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(K-v)).argmin()
print(K[index])

87


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [50]:
K = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(K)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\TURBULENCE\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [124]:
K = np.random.random((10,2))
X,Y = np.atleast_2d(K[:,0], K[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy

import scipy.spatial

K = np.random.random((10,2))
D = scipy.spatial.distance.cdist(K,K)
print(D)

[[0.         0.20022733 0.78279743 0.81487118 0.49972616 0.81664794
  0.39010388 0.09590956 0.09524601 0.56923754]
 [0.20022733 0.         0.82522725 0.9148742  0.67653612 0.85241765
  0.22153792 0.17294055 0.11959068 0.7638178 ]
 [0.78279743 0.82522725 0.         0.26396565 0.61603788 0.0414301
  0.75632828 0.87056521 0.75750676 1.04983642]
 [0.81487118 0.9148742  0.26396565 0.         0.48028397 0.29163196
  0.90630382 0.91026651 0.82057216 0.92515198]
 [0.49972616 0.67653612 0.61603788 0.48028397 0.         0.65739222
  0.785426   0.58697978 0.55746533 0.44623811]
 [0.81664794 0.85241765 0.0414301  0.29163196 0.65739222 0.
  0.77450814 0.90324449 0.78835559 1.09117519]
 [0.39010388 0.22153792 0.75632828 0.90630382 0.785426   0.77450814
  0.         0.39063275 0.29486056 0.95724053]
 [0.09590956 0.17294055 0.87056521 0.91026651 0.58697978 0.90324449
  0.39063275 0.         0.12745235 0.60041846]
 [0.09524601 0.11959068 0.75750676 0.82057216 0.55746533 0.78835559
  0.29486056 0.127452

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [125]:
K = (np.random.rand(10)*100).astype(np.float32)
M = K.view(np.int32)
M[:] = K
print(M)

[42 98 45 15 63  9 89 62 84 87]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [53]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [126]:
K = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(K):
    print(index, value)
print()
for index in np.ndindex(K.shape):
    print(index, K[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [55]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [56]:
n = 10
p = 3
K = np.zeros((n,n))
np.put(K, np.random.choice(range(n*n), p, replace=False),1)
print(K)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [57]:
A = np.random.rand(5, 10)

# Recent versions of numpy
B = A - A.mean(axis=1, keepdims=True)

# Older versions of numpy
B = A - A.mean(axis=1).reshape(-1, 1)

print(B)

[[-0.28977205  0.47597012  0.66421095 -0.25877533  0.04684514  0.25998031
  -0.22169225 -0.13934414 -0.25212529 -0.28529745]
 [-0.38389825 -0.43586772  0.22571479  0.37746812  0.37065829 -0.59157954
   0.35324656  0.27004426 -0.15135691 -0.0344296 ]
 [-0.1517372  -0.39695225  0.20909429  0.32055021  0.42196563 -0.19605675
  -0.30000571 -0.05605612  0.5387854  -0.3895875 ]
 [-0.16290824 -0.32680769  0.19128451  0.23663938  0.10634741  0.47162969
  -0.37238576  0.19243621 -0.10468453 -0.23155097]
 [ 0.48452282  0.10305525 -0.19711816 -0.06091302 -0.04584224 -0.11948219
   0.2675254  -0.22324797 -0.38671382  0.17821392]]


#### 59. How to sort an array by the nth column? (★★☆)

In [58]:
K = np.random.randint(0,20,(4,4))
print(K)
print()
print(K[K[:,2].argsort()])

[[10 18 16  5]
 [ 9 19 12  8]
 [17 13  2 10]
 [ 3  1 19  6]]

[[17 13  2 10]
 [ 9 19 12  8]
 [10 18 16  5]
 [ 3  1 19  6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [59]:
K = np.random.randint(0,3,(3,10))
print((~K.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [60]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5529738214948189


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [129]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
itr = np.nditer([A,B,None])
for x,y,z in itr: 
    z[...] = x + y
print(itr.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [130]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

K = NamedArray(np.arange(10), "range_10")
print (K.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [132]:
K = np.ones(10)
I = np.random.randint(0,len(K),20)
K += np.bincount(I, minlength=len(K))
print(K)



[2. 3. 5. 3. 4. 1. 5. 2. 4. 1.]


In [66]:
# Another solution
np.add.at(Z, I, 1)
print(Z)

[ 5.  1.  7.  5.  3. 11.  1.  5.  5.  7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [69]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [70]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[43 48 55 61]
 [67 65 51 55]
 [60 49 69 65]]
[[43 48 55 61]
 [67 65 51 55]
 [60 49 69 65]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [78]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.58842769 0.55977458 0.51769475 0.48664848 0.48898702 0.47457062
 0.43677093 0.26420362 0.35729001 0.5199068 ]


In [79]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.588428
1    0.559775
2    0.517695
3    0.486648
4    0.488987
5    0.474571
6    0.436771
7    0.264204
8    0.357290
9    0.519907
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [80]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [81]:
# Slow version
np.diag(np.dot(A, B))

array([1.42474786, 0.53304043, 0.7841772 , 0.8388753 , 1.14133607])

In [82]:
# Fast version
np.sum(A * B.T, axis=1)

array([1.42474786, 0.53304043, 0.7841772 , 0.8388753 , 1.14133607])

In [83]:
# Faster version
np.einsum("ij,ji->i", A, B)

array([1.42474786, 0.53304043, 0.7841772 , 0.8388753 , 1.14133607])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [84]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [85]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [86]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [88]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 5,  7) ( 5, 33) ( 7, 33) ( 7, 88) ( 7, 89) ( 8, 33) ( 8, 78) (10, 27)
 (10, 71) (12, 36) (12, 99) (20, 24) (20, 47) (20, 79) (20, 82) (24, 82)
 (26, 42) (26, 97) (27, 71) (33, 78) (36, 99) (42, 44) (42, 89) (42, 97)
 (44, 89) (47, 79) (72, 75) (72, 81) (75, 81) (88, 89)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [89]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [133]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
K = np.arange(20)
print(moving_average(K, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [134]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
K = rolling(np.arange(10), 3)
print(K)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [135]:
K = np.random.randint(0,2,100)
np.logical_not(K, out=K)

K = np.random.uniform(-1.0,1.0,100)
np.negative(K, out=K)

array([-0.51103266, -0.24230037,  0.23260507, -0.17638152, -0.26160024,
        0.83120955,  0.94804377, -0.2346326 , -0.33628489,  0.99204298,
       -0.5262275 , -0.59710756, -0.64706794, -0.56257963,  0.93218246,
       -0.23851542, -0.56523979,  0.77362997,  0.03312523,  0.13478377,
       -0.22831301,  0.25465633,  0.73444803, -0.03325959,  0.71011971,
       -0.76527117,  0.81925565, -0.84555591, -0.98473407,  0.90857677,
        0.80006659,  0.49310884,  0.96401864,  0.49088606,  0.91925884,
        0.37409639,  0.46575128, -0.0641068 , -0.49455106, -0.69724137,
        0.50380099,  0.01584843, -0.17969076,  0.01614202,  0.83735626,
       -0.01853754, -0.35789668,  0.6574836 , -0.76477785,  0.08221077,
       -0.25501392, -0.50037792,  0.66268647, -0.66641122, -0.62892723,
        0.92101687, -0.0939315 , -0.4273137 ,  0.21184844,  0.65075935,
        0.4539111 ,  0.03690056,  0.90223661, -0.69377958,  0.25901633,
       -0.57298553,  0.59707984,  0.10405077, -0.80057684, -0.78

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [93]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.04107661 4.0464042  0.93275335 5.44255397 0.34078648 2.33250307
 8.37843526 3.54552178 7.12537424 3.5626935 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [94]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.04878975 14.72020337  2.65003296  1.7375846   4.41098865  2.30305264
  14.98027473  1.43904904  2.98697412  5.19101831]
 [ 4.26904526 10.17905118  0.51408515  3.87599066  2.95269693  4.17295026
  10.61872854  3.73965784  2.01627868  2.32322479]
 [ 8.6383112   0.41469593  7.50502498  6.45284593 10.69494999 17.77780187
   0.23834859  8.78031745  2.19119979 10.73232295]
 [ 4.16281415  4.37783299  4.126812    6.17537409  0.78526306  6.83932512
   5.0179221  10.17879797  8.10126362  1.53987469]
 [ 9.31709969  7.88106832 13.05810455 10.32195963  8.54604999 14.9302001
   7.38570344  0.12147952  6.28538151  6.18024728]
 [ 4.25731553 12.67999656  1.10711091  2.82053788  3.84189987  3.06466153
  13.02896637  0.93749846  0.65249859  3.95901589]
 [ 2.88861078  2.38587485  3.99623392  5.58419189  0.93132139  8.64140711
   3.00207529 11.82605669  9.21173584  3.50359193]
 [ 9.80124837 11.46204864  5.817297    9.51257836  7.75967389  0.36240166
  12.26999673  4.82460493  5.02738096  6.01376976]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [96]:

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print()
print(R)

[[7 8 4 0 5 0 3 8 0 1]
 [0 7 3 5 2 9 2 0 7 0]
 [5 0 8 7 4 1 7 3 0 3]
 [7 8 2 4 7 6 5 8 4 7]
 [7 9 4 6 1 4 1 8 8 2]
 [1 9 7 2 3 5 4 2 6 8]
 [6 6 5 5 2 1 9 4 2 6]
 [5 0 2 5 8 8 2 0 6 2]
 [3 0 5 9 8 4 5 9 0 5]
 [9 4 1 3 1 9 3 3 1 8]]

[[0 0 0 0 0]
 [0 7 8 4 0]
 [0 0 7 3 5]
 [0 5 0 8 7]
 [0 7 8 2 4]]


C:\Users\TURBULENCE\anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array K = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array M = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [137]:
K = np.arange(1,15,dtype=np.uint32)
M = stride_tricks.as_strided(Z,(11,4),(4,4))
print(M)

[[1 0 1 1]
 [0 1 1 1]
 [1 1 1 0]
 [1 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### 82. Compute a matrix rank (★★★)

In [138]:
K = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(K) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [139]:
K = np.random.randint(0,10,50)
print(np.bincount(K).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [100]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 2]
   [2 0 2]
   [4 0 2]]

  [[0 2 3]
   [0 2 4]
   [0 2 1]]

  [[2 3 0]
   [2 4 0]
   [2 1 3]]

  [[3 0 3]
   [4 0 3]
   [1 3 0]]

  [[0 3 4]
   [0 3 0]
   [3 0 3]]

  [[3 4 0]
   [3 0 3]
   [0 3 4]]

  [[4 0 2]
   [0 3 4]
   [3 4 4]]

  [[0 2 4]
   [3 4 2]
   [4 4 4]]]


 [[[2 0 2]
   [4 0 2]
   [3 0 1]]

  [[0 2 4]
   [0 2 1]
   [0 1 2]]

  [[2 4 0]
   [2 1 3]
   [1 2 3]]

  [[4 0 3]
   [1 3 0]
   [2 3 1]]

  [[0 3 0]
   [3 0 3]
   [3 1 1]]

  [[3 0 3]
   [0 3 4]
   [1 1 4]]

  [[0 3 4]
   [3 4 4]
   [1 4 2]]

  [[3 4 2]
   [4 4 4]
   [4 2 2]]]


 [[[4 0 2]
   [3 0 1]
   [2 2 2]]

  [[0 2 1]
   [0 1 2]
   [2 2 1]]

  [[2 1 3]
   [1 2 3]
   [2 1 0]]

  [[1 3 0]
   [2 3 1]
   [1 0 4]]

  [[3 0 3]
   [3 1 1]
   [0 4 2]]

  [[0 3 4]
   [1 1 4]
   [4 2 2]]

  [[3 4 4]
   [1 4 2]
   [2 2 2]]

  [[4 4 4]
   [4 2 2]
   [2 2 4]]]


 [[[3 0 1]
   [2 2 2]
   [3 4 0]]

  [[0 1 2]
   [2 2 1]
   [4 0 1]]

  [[1 2 3]
   [2 1 0]
   [0 1 4]]

  [[2 3 1]
   [1 0 4]
   [1 4 0]]

  [[3 1 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [101]:

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  9  6 12  6]
 [ 9  0 13  0  3]
 [ 6 13  8 42  8]
 [12  0 42  4  9]
 [ 6  3  8  9  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [102]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [103]:

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [104]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [141]:
K = np.arange(10000)
np.random.shuffle(K)
n = 5

# Slow
print (K[np.argsort(K)[-n:]])



[9995 9996 9997 9998 9999]


In [106]:
# Fast
print (K[np.argpartition(-K,n)[:n]])

[9998 9996 9999 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [107]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [108]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [109]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

6.19 s ± 84.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.36 s ± 94.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
757 ms ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [110]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [111]:
K = np.random.randint(0,5,(10,3))
print(K)


[[1 1 1]
 [0 2 1]
 [0 0 1]
 [2 3 3]
 [2 4 2]
 [1 1 2]
 [0 2 1]
 [1 4 0]
 [0 4 3]
 [0 0 1]]


In [112]:
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)


[[0 2 1]
 [0 0 1]
 [2 3 3]
 [2 4 2]
 [1 1 2]
 [0 2 1]
 [1 4 0]
 [0 4 3]
 [0 0 1]]


In [113]:
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 2 1]
 [0 0 1]
 [2 3 3]
 [2 4 2]
 [1 1 2]
 [0 2 1]
 [1 4 0]
 [0 4 3]
 [0 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [114]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [115]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [116]:
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 2 1]
 [0 4 3]
 [1 1 1]
 [1 1 2]
 [1 4 0]
 [2 3 3]
 [2 4 2]]


In [117]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [118]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.23492815, 0.24054618, 0.24978537, 0.31567982, 0.28795592,
        0.08703565, 0.38653467, 0.17678276, 0.12307186, 0.00456323],
       [0.18388205, 0.18827936, 0.19551103, 0.24708767, 0.22538773,
        0.06812421, 0.3025469 , 0.13837071, 0.09633032, 0.00357171],
       [0.47831643, 0.4897548 , 0.5085659 , 0.64272775, 0.58628157,
        0.1772056 , 0.78698905, 0.35993175, 0.25057572, 0.00929078],
       [0.14439642, 0.14784948, 0.15352827, 0.19402968, 0.17698944,
        0.05349566, 0.23757996, 0.10865789, 0.07564498, 0.00280474],
       [0.09233647, 0.09454458, 0.09817597, 0.12407521, 0.11317857,
        0.03420861, 0.15192409, 0.06948293, 0.04837232, 0.00179354],
       [0.05988261, 0.06131463, 0.06366968, 0.08046601, 0.07339926,
        0.02218517, 0.09852674, 0.04506149, 0.03137071, 0.00116316],
       [0.04713787, 0.04826512, 0.05011895, 0.06334054, 0.05777779,
        0.01746353, 0.07755743, 0.03547112, 0.02469413, 0.0009156 ],
       [0.49916037, 0.51109719, 0.5307280

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [142]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [120]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [121]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22044172  0.15735146]
