## Constructeurs

In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3])
A.ndim
A.shape

(3,)

In [3]:
# un tableau de zeros
B = np.zeros((3,2))
type(B.shape)

tuple

In [4]:
c = np.ones((3,4))
c.size

12

In [5]:
D = np.full((2,3),9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [6]:
#nombres aleatoires issus d'une distribution normale centrée
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [7]:
#matrice d'identité
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#tableau à une dimension dans lequel on va préciser valleun nombre de debut de fin et combien de nombres dans cet inter
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
#tableau à une dimension dans lequel on va préciser le debut fin et le pas
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
#préciser le type de données que l'on veut
np.linspace(0,20,10,dtype=np.float16)

array([ 0.   ,  2.223,  4.445,  6.668,  8.89 , 11.11 , 13.336, 15.555,
       17.78 , 20.   ], dtype=float16)

## Manipulation

In [11]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [12]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
#methode hstack et vstack
c= np.hstack((A,B))

In [15]:
D = np.vstack((A,B))
D.shape

(6, 2)

In [16]:
np.concatenate((A,B), axis = 0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.concatenate((A,B), axis = 1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [18]:
# methode reshape
D = D.reshape((3,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# très utile pour les tableau à 1 dimension car peut poser pbl dans certains algo
A = np.array([1,2,3])
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)

In [20]:
#pour revenir à la shape de base
A = A.squeeze()

In [21]:
A.shape

(3,)

In [22]:
#methode ravel() applatit les tableaux peut être utile parfois
D.ravel().shape



(12,)

In [23]:
def initialisation(m,n):
    A = np.random.randn(m,n)
    
    B = np.ones((m,1))
    C = np.concatenate((A,B),axis = 1)
    
    
    return C

In [24]:
initialisation(3,2)

array([[ 0.76103773,  0.12167502,  1.        ],
       [ 0.44386323,  0.33367433,  1.        ],
       [ 1.49407907, -0.20515826,  1.        ]])

## Indexing

In [25]:

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
A.shape

(3, 3)

In [27]:
A[0,0]

1

In [28]:
A[1,1]

5

In [29]:
A[:,0]

array([1, 4, 7])

In [30]:
A[0,:]

array([1, 2, 3])

In [31]:
A[0]

array([1, 2, 3])

In [32]:
#subsetting
B = A[0:2, 0:2]

In [33]:
B.shape

(2, 2)

In [34]:
A[0:2,0:2] = 10

In [35]:
A

array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

## Slicing 

A = [debut:fin:pas, debut:fin:pas]

In [36]:
#recuperer juste le 
A[:, -2:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [37]:
B = np.zeros((4,4))

In [38]:
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
B[1:3,1:3]=1

In [40]:
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [41]:
C = np.zeros((5,5))

In [42]:
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
C[::2,::2]=1

In [44]:
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

## Boolean Indexing

In [45]:
A = np.random.randint(0,10,[5,5])

In [46]:
A

array([[7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [47]:
A<5

array([[False,  True,  True, False, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [ True,  True, False, False,  True]])

In [48]:
A[A<5]=10

In [49]:
A

array([[ 7, 10, 10,  9,  9],
       [10, 10,  7, 10, 10],
       [ 7, 10, 10, 10, 10],
       [ 5,  5,  6,  8, 10],
       [10, 10,  9,  8, 10]])