# PyTorch - Beginners Tutorial 1

- Supported/developed by Facebook

## Alternatives

- [Tensorflow](https://www.tensorflow.org/)
- [Keras](https://keras.io/)
- [Theano](http://deeplearning.net/software/theano/)
- [Caffe](http://caffe.berkeleyvision.org/)
- [Caffe2](https://caffe2.ai/)
- [MXNet](https://mxnet.apache.org/)

## Why PyTorch?

- Simple Python
- Easy to use + debug
- Simple and extensible interface (modules, etc.)


____

# Import the Libraries `numpy` and `torch`

In [4]:
import torch
import numpy as np

In [5]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>")) # use full width of screen for cell area 

### Check your PyTorch version

In [6]:
print("PyTorch Version:", torch.__version__)

PyTorch Version: 1.11.0


### NOTE: 
#### Although this is a PyTorch tutorial course, we'll also compare and contrast the library with another popular mathematics library, Numpy

# Tensors

## Definition of a `Tensor`

A **matrix** is a grid of numbers, let's say (3x5). In simple terms, a **tensor** can be seen as a generalization of a matrix to higher dimension. It can be of arbitrary shape, for example;<br>  dim = \[3 x 2 x 4 x 5\]
<br>

For now, just think of tensors as multidimensional arrays.

### Creating our first torch Tensor

In [7]:
X = torch.tensor([1, 2, 3, 4, 5])

In [8]:
print(f'X is represented as;\n {X} \n\nX is of type:\n {type(X)}')

X is represented as;
 tensor([1, 2, 3, 4, 5]) 

X is of type:
 <class 'torch.Tensor'>


Use the `.shape` method to access the dimension attribute of the tensor

In [9]:
X.shape

torch.Size([5])

#### This indicates and array of length 5

#### Adding square brackets around the array however changes that to an n dimensional matrix form:<br>
    X = torch.tensor( [ [1, 2, 3, 4, 5 ] ])

In [10]:
X = torch.tensor( [ [1, 2, 3, 4, 5 ] ])

In [11]:
X

tensor([[1, 2, 3, 4, 5]])

#### We see the printout is almost identicle to the previous case, but these two objects are distinct in their interpretation, as can be proven by using .shape on the new X variable

In [12]:
X.shape

torch.Size([1, 5])

## Syntax for constructing tensors

In [13]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [14]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

We see to create a n x m object we pass `n arrays` (rows) consisting of a `m elements` (columns)

In [15]:
X.shape

torch.Size([2, 3])

# `Numpy arrays` and `Torch tensors`

### The `Identity` matrix of dimension n:
(using numpy) Generate a 3x3 Identity:

In [16]:
np_eye = np.eye(3)

In [17]:
np_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

(using torch) Generate a 3x3 Identity:

In [18]:
torch_eye = torch.eye(3)

In [19]:
torch_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Scalar Multipled By tensor
(using numpy) 

In [20]:
5*np_eye

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

### Scalar Multipled By tensor
(using torch)

In [21]:
5*torch_eye

tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.]])

### The `null` vector of dim 1 x n:
(using numpy) Generate an 1 x n array 

In [22]:
np_null = np.zeros(5)

In [23]:
np_null

array([0., 0., 0., 0., 0.])

### The `null` vector of dim 1 x n:
(using torch) Generate an 1 x n array 

In [24]:
torch_null = torch.zeros(5)

## Using `.empty` 
Return an n x m Matrix without initializing entries. 

`empty`, unlike `zeros`, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.


(using numpy)

In [25]:
np_empty = np.empty((3, 5))

In [26]:
np_empty

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

(using torch)

In [27]:
torch_empty = torch.empty((3, 5))

In [28]:
torch_empty

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.4995e-36, 1.4013e-45, 2.4995e-36, 1.4013e-45],
        [1.4314e-36, 1.4013e-45, 1.4314e-36, 1.4013e-45, 1.4315e-36]])

What if we wanted to only include integers as follows:<br>
 Identical syntax for both torch and numpy

In [29]:
np_empty = np.empty((3, 5), dtype=int)

In [30]:
torch_empty = torch.empty((3, 5), dtype=int)

In [31]:
np_empty

array([[                  0,                   0, 4601727903846100441,
        4587820456862672466, 4595745948572889240],
       [4601727903846100441, 4596827656117413458, 4600249548200259736,
        4601727903846100441, 4602288710223143708],
       [4603108665757041778, 4601727903846100441, 4605834855372154450,
        4604753147827630232, 4601727903846100441]])

In [32]:
torch_empty

tensor([[4361551884, 4383646768, 4370044784, 4361572592, 4390226480],
        [4368794096, 4370870512, 4410525360, 4424267776, 4388762736],
        [4424277584, 4361451376, 4418464816, 4361301872, 4368345584]])

## Create a `Random Matrix` with dimension n x m

In [33]:
Y = torch.rand((4, 7))

In [34]:
Y

tensor([[0.0759, 0.4692, 0.7490, 0.8110, 0.5990, 0.3588, 0.8358],
        [0.5614, 0.1851, 0.5052, 0.3958, 0.7610, 0.2335, 0.9439],
        [0.3146, 0.6173, 0.6574, 0.9392, 0.1363, 0.6934, 0.5050],
        [0.2870, 0.0113, 0.0797, 0.7232, 0.6287, 0.4614, 0.8493]])

In [35]:
Y.shape

torch.Size([4, 7])

___

### So far we've seen that torch tensors and numpy array behave essentially identically

##  Then, the question remains....

## <span style="color:red">Why do we even need tensors if we can do exactly the same with numpy arrays?</span>

# NOTE: `torch.tensor` behaves identically to numpy arrays under mathematical operations. The difference is that; 
$\newline$
<span style="color:blue; font-size:150%"> $$\textbf{By using torch tensors we keep track of the gradients and also are GPU compatible/ready/optimized}$$</span>

____

# Matrix Operations

In [36]:
X = np.random.rand(2, 7)
X

array([[0.63374808, 0.0206833 , 0.97602621, 0.58682536, 0.43484104,
        0.45209063, 0.1906537 ],
       [0.39799494, 0.6279665 , 0.92088417, 0.2250535 , 0.94889734,
        0.6873814 , 0.26843019]])

In [37]:
Y = torch.rand(2, 7)
Y

tensor([[0.9340, 0.7606, 0.2199, 0.3199, 0.5679, 0.8068, 0.8926],
        [0.2485, 0.8607, 0.9057, 0.1163, 0.5110, 0.8884, 0.1873]])

## Matrix Multiplication 
###  NOTE: Operator `*` does element-wise multiplication, in both torch and numpy

### Matrix Multiplication 
(numpy way)

In [38]:
output_np = X.T @ X

In [39]:
output_np

array([[0.5600366 , 0.2630355 , 0.98506198, 0.4614696 , 0.65323601,
        0.56008589, 0.22766027],
       [0.2630355 , 0.39476973, 0.59847186, 0.15346355, 0.60486969,
        0.44100322, 0.17250852],
       [0.98506198, 0.59847186, 1.80065482, 0.78000514, 1.29824078,
        1.07425095, 0.43327612],
       [0.4614696 , 0.15346355, 0.78000514, 0.39501308, 0.46872841,
        0.41999584, 0.17229158],
       [0.65323601, 0.60486969, 1.29824078, 0.46872841, 1.08949288,
        0.84884193, 0.33761675],
       [0.56008589, 0.44100322, 1.07425095, 0.41999584, 0.84884193,
        0.67687912, 0.27070667],
       [0.22766027, 0.17250852, 0.43327612, 0.17229158, 0.33761675,
        0.27070667, 0.1084036 ]])

In [40]:
output_np.shape

(7, 7)

### Matrix Multiplication 
(torch way)

`Y.t() * Y`  # error, dimensions do not match for element-wise multiplication

In [56]:
output_torch = Y.t() @ Y

In [57]:
output_torch

tensor([[0.9341, 0.9242, 0.4304, 0.3277, 0.6574, 0.9743, 0.8802],
        [0.9242, 1.3192, 0.9467, 0.3434, 0.8717, 1.3782, 0.8400],
        [0.4304, 0.9467, 0.8686, 0.1757, 0.5877, 0.9820, 0.3659],
        [0.3277, 0.3434, 0.1757, 0.1159, 0.2411, 0.3615, 0.3073],
        [0.6574, 0.8717, 0.5877, 0.2411, 0.5836, 0.9121, 0.6025],
        [0.9743, 1.3782, 0.9820, 0.3615, 0.9121, 1.4402, 0.8865],
        [0.8802, 0.8400, 0.3659, 0.3073, 0.6025, 0.8865, 0.8317]])

In [58]:
output_torch

tensor([[0.9341, 0.9242, 0.4304, 0.3277, 0.6574, 0.9743, 0.8802],
        [0.9242, 1.3192, 0.9467, 0.3434, 0.8717, 1.3782, 0.8400],
        [0.4304, 0.9467, 0.8686, 0.1757, 0.5877, 0.9820, 0.3659],
        [0.3277, 0.3434, 0.1757, 0.1159, 0.2411, 0.3615, 0.3073],
        [0.6574, 0.8717, 0.5877, 0.2411, 0.5836, 0.9121, 0.6025],
        [0.9743, 1.3782, 0.9820, 0.3615, 0.9121, 1.4402, 0.8865],
        [0.8802, 0.8400, 0.3659, 0.3073, 0.6025, 0.8865, 0.8317]])

In [59]:
output_torch.shape

torch.Size([7, 7])

# Using `matmul` 

<h2>We use matmul when we would like to computer the `Matrix product` of two tensors.</h2>

<b>NOTE: The behavior depends on the dimensionality of the tensors as follows:</b>
<ul>
<li>If both tensors are 1-dimensional, the dot product (scalar) is returned.</li>

<li>If both arguments are 2-dimensional, the matrix-matrix product is returned.</li>

<li>If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed.</li>

<li>If the first argument is 2-dimensional and the second argument is 1-dimensional, the matrix-vector product is returned.</li>

<li>If both arguments are at least 1-dimensional and at least one argument is N-dimensional (where N > 2), then a batched matrix multiply is returned. If the first argument is 1-dimensional, a 1 is prepended to its dimension for the purpose of the batched matrix multiply and removed after. If the second argument is 1-dimensional, a 1 is appended to its dimension for the purpose of the batched matrix multiple and removed after. The non-matrix (i.e. batch) dimensions are broadcasted (and thus must be broadcastable). For example, if input is a (j×1×n×n) tensor and other is a (k×n×n) tensor, out will be a (j×k×n×n) tensor.<br>
Note that the broadcasting logic only looks at the batch dimensions when determining if the inputs are broadcastable, and not the matrix dimensions. For example, if input is a (j×1×n×m) tensor and other is a (k×m×p) tensor, these inputs are valid for broadcasting even though the final two dimensions (i.e. the matrix dimensions) are different. out will be a (j×k×n×p) tensor.
</ul>
This operator supports TensorFloat32.

<b>NOTE:The 1-dimensional dot product version of this function does not support an out parameter.</b>

In [78]:
Y.t().matmul(Y)

tensor([[0.9341, 0.9242, 0.4304, 0.3277, 0.6574, 0.9743, 0.8802],
        [0.9242, 1.3192, 0.9467, 0.3434, 0.8717, 1.3782, 0.8400],
        [0.4304, 0.9467, 0.8686, 0.1757, 0.5877, 0.9820, 0.3659],
        [0.3277, 0.3434, 0.1757, 0.1159, 0.2411, 0.3615, 0.3073],
        [0.6574, 0.8717, 0.5877, 0.2411, 0.5836, 0.9121, 0.6025],
        [0.9743, 1.3782, 0.9820, 0.3615, 0.9121, 1.4402, 0.8865],
        [0.8802, 0.8400, 0.3659, 0.3073, 0.6025, 0.8865, 0.8317]])

## Finding the inverse

(numpy way)

In [79]:
np.linalg.inv(X.T @ X)

LinAlgError: Singular matrix

## Finding the inverse
(torch way)

In [82]:
torch.inverse(Y.t() @ Y)

tensor([[ 7.7987e+06, -2.8519e+06,  2.9699e+06, -8.8341e+06,  6.0792e+06,
         -4.0476e+06, -3.5048e+06],
        [-6.0243e+06,  3.3460e+04,  5.9680e+06,  1.4710e+07,  2.8719e+07,
         -2.3384e+07,  2.3997e+06],
        [ 8.6990e+06,  2.7907e+06, -8.5764e+06,  1.6453e+07, -2.6173e+07,
          2.0034e+07, -1.6724e+07],
        [ 7.3621e+06,  1.6728e+07,  3.4493e+07,  7.0655e+07,  6.2351e+06,
         -6.6310e+07,  1.9524e+05],
        [ 2.4299e+07,  2.0387e+07, -2.6256e+07, -3.1388e+07, -8.3792e+07,
          5.7546e+07, -2.3791e+07],
        [-1.8840e+07, -1.5415e+07,  1.6166e+07, -2.1092e+07,  4.8079e+07,
         -2.7678e+07,  3.0859e+07],
        [-6.2379e+06, -2.7634e+06, -1.6353e+07,  6.3683e+06, -1.6773e+07,
          3.1402e+07, -7.0871e+06]])

# Creating Sequential Arrays and Matrices

(numpy way)

In [83]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

(torch way)

In [84]:
torch.arange(2, 10, 2)

tensor([2, 4, 6, 8])

Using `linspace` to generate N equally spaced values on a given interval:

In [85]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [86]:
torch.linspace(0, 1, 10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

## More on PyTorch Tensors

Each operation is also available as a function.

In [87]:
X = torch.rand(3, 2)

In [88]:
torch.exp(X)

tensor([[2.6034, 1.1031],
        [2.0445, 1.9785],
        [2.4678, 1.0449]])

In [89]:
X.exp()

tensor([[2.6034, 1.1031],
        [2.0445, 1.9785],
        [2.4678, 1.0449]])

In [90]:
X.sqrt()

tensor([[0.9782, 0.3132],
        [0.8457, 0.8260],
        [0.9504, 0.2096]])

In [91]:
(X.exp() + 2).sqrt() - 2 * X.log().sigmoid()  # be creative :-)

tensor([[1.1676, 1.5829],
        [1.1772, 1.1834],
        [1.1645, 1.6608]])

Many more functions available: sin, cos, tanh, log, etc.

In [92]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [93]:
A.add(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [94]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Functions that mutate (in-place) the passed object end with an underscore, e.g. *add_*, *div_*, etc.

In [95]:
A.add_(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [96]:
A

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [97]:
A.div_(3)

tensor([[2.0000, 1.6667, 1.6667],
        [1.6667, 2.0000, 1.6667],
        [1.6667, 1.6667, 2.0000]])

In [98]:
A

tensor([[2.0000, 1.6667, 1.6667],
        [1.6667, 2.0000, 1.6667],
        [1.6667, 1.6667, 2.0000]])

In [99]:
A.uniform_()  # fills the tensor with random uniform numbers in [0, 1]

tensor([[0.8401, 0.5917, 0.8291],
        [0.1315, 0.1547, 0.9701],
        [0.1359, 0.0727, 0.8224]])

In [100]:
A

tensor([[0.8401, 0.5917, 0.8291],
        [0.1315, 0.1547, 0.9701],
        [0.1359, 0.0727, 0.8224]])

# Indexing and Slicing

Again, it works just like in numpy.

In [101]:
A = torch.randint(100, (3, 3))
A

tensor([[77, 50, 26],
        [72, 27, 92],
        [88, 74, 94]])

In [102]:
A[0, 0]

tensor(77)

In [103]:
A[2, 1]

tensor(74)

In [104]:
A[1]

tensor([72, 27, 92])

In [105]:
A[:, 1]

tensor([50, 27, 74])

In [106]:
A[1:2, :], A[1:2, :].shape

(tensor([[72, 27, 92]]), torch.Size([1, 3]))

In [107]:
A[1:, 1:]

tensor([[27, 92],
        [74, 94]])

In [108]:
A[:2, :2]

tensor([[77, 50],
        [72, 27]])

_____

## Reshaping & Expanding

In [109]:
X = torch.tensor([1, 2, 3, 4])
X

tensor([1, 2, 3, 4])

In [110]:
X = X.repeat(3, 1) # repeat it 3 times along 0th dimension and 1 times along first dimension
X, X.shape

(tensor([[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]),
 torch.Size([3, 4]))

In [111]:
# equivalent of 'reshape' in numpy (view does not allocate new memory!)
Y = X.view(2, 6)
Y

tensor([[1, 2, 3, 4, 1, 2],
        [3, 4, 1, 2, 3, 4]])

In [112]:
Y = X.view(-1)  # -1 tells PyTorch to infer the number of elements along that dimension
Y, Y.shape

(tensor([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]), torch.Size([12]))

In [113]:
Y = X.view(-1, 2)
Y, Y.shape

(tensor([[1, 2],
         [3, 4],
         [1, 2],
         [3, 4],
         [1, 2],
         [3, 4]]),
 torch.Size([6, 2]))

In [114]:
Y = X.view(-1, 4)
Y, Y.shape

(tensor([[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]),
 torch.Size([3, 4]))

In [115]:
Y = torch.ones(5)
Y, Y.shape

(tensor([1., 1., 1., 1., 1.]), torch.Size([5]))

In [116]:
Y = Y.view(-1, 1)
Y, Y.shape

(tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]),
 torch.Size([5, 1]))

In [117]:
Y.expand(5, 5)  # similar to repeat but does not actually allocate new memory

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [118]:
X = torch.eye(4)
Y = X[3:, :]
Y, Y.shape

(tensor([[0., 0., 0., 1.]]), torch.Size([1, 4]))

In [119]:
Y = Y.squeeze() # removes all dimensions of size '1'
Y, Y.shape

(tensor([0., 0., 0., 1.]), torch.Size([4]))

In [120]:
Y = Y.unsqueeze(1)
Y, Y.shape

(tensor([[0.],
         [0.],
         [0.],
         [1.]]),
 torch.Size([4, 1]))

## Reductions

In [121]:
X = torch.randint(10, (3, 4)).float()
X

tensor([[8., 9., 5., 5.],
        [9., 8., 0., 6.],
        [7., 0., 8., 5.]])

In [122]:
X.sum()

tensor(70.)

In [123]:
X.sum().item()

70.0

In [124]:
X.sum(0) # colum-wise sum

tensor([24., 17., 13., 16.])

In [125]:
X.sum(dim=1)  # row-wise sum

tensor([27., 23., 20.])

In [126]:
X.mean()

tensor(5.8333)

In [127]:
X.mean(dim=1)

tensor([6.7500, 5.7500, 5.0000])

In [128]:
X.norm(dim=0)

tensor([13.9284, 12.0416,  9.4340,  9.2736])

## Exercises:

Compute the norms of the row-vectors in matrix **X** without using _torch.norm()_.

Remember: $$||\vec{v}||_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}$$

Hint: _X\*\*2_ computes the element-wise square.

In [129]:
X = torch.eye(4) + torch.arange(4).repeat(4, 1).float()

In [130]:
# Answer here

## Masking

In [131]:
X = torch.randint(100, (5, 3))
X

tensor([[51, 93, 46],
        [54, 26,  6],
        [27, 80, 44],
        [42, 72, 45],
        [14, 66, 50]])

In [132]:
mask = (X > 25) & (X < 75)
mask

tensor([[ True, False,  True],
        [ True,  True, False],
        [ True, False,  True],
        [ True,  True,  True],
        [False,  True,  True]])

In [133]:
X[mask]  # returns all elements matching the criteria in a 1D-tensor

tensor([51, 46, 54, 26, 27, 44, 42, 72, 45, 66, 50])

In [134]:
mask.sum()  # number of elements that fulfill the condition

tensor(11)

In [135]:
(X == 25) | (X > 60)

tensor([[False,  True, False],
        [False, False, False],
        [False,  True, False],
        [False,  True, False],
        [False,  True, False]])

## Exercise

Get the number of non-zeros in **X**

In [137]:
X = torch.tensor([[1, 0, 2], [0, 6, 0]])

Compute the sum of all entries in X that are larger than the mean of all values in X.

In [138]:
# compute here

______

## Some useful properties of tensors

In [139]:
x = torch.Tensor([[0,1,2], [3,4,5]])

print("x.shape: \n%s\n" % (x.shape,))
print("x.size(): \n%s\n" % (x.size(),))
print("x.size(1): \n%s\n" % x.size(1))
print("x.dim(): \n%s\n" % x.dim())

print("x.dtype: \n%s\n" % x.dtype)
print("x.device: \n%s\n" % x.device)

x.shape: 
torch.Size([2, 3])

x.size(): 
torch.Size([2, 3])

x.size(1): 
3

x.dim(): 
2

x.dtype: 
torch.float32

x.device: 
cpu



The `nonzero` function returns indices of the non zero elements.

In [140]:
x = torch.Tensor([[0,1,2], [3,4,5]])

print("x.nonzero(): \n%s\n" % x.nonzero())

x.nonzero(): 
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])



In [141]:
# press tab to autocomplete
# x.

___

# Converting between PyTorch and numpy

In [148]:
X = np.random.random((5,3))
X

array([[0.20819822, 0.5563592 , 0.92248158],
       [0.63995137, 0.73778404, 0.50722448],
       [0.89128372, 0.67346384, 0.8118839 ],
       [0.15679724, 0.83647956, 0.07266985],
       [0.35856279, 0.81994211, 0.15187409]])

# Converting `Numpy` $\rightarrow$ `Torch`

In [149]:
Y = torch.from_numpy(X)
Y

tensor([[0.2082, 0.5564, 0.9225],
        [0.6400, 0.7378, 0.5072],
        [0.8913, 0.6735, 0.8119],
        [0.1568, 0.8365, 0.0727],
        [0.3586, 0.8199, 0.1519]], dtype=torch.float64)

## Y is actually a `DoubleTensor` (i.e. `64-bit` representation)

In [150]:
Y = torch.rand((2,4))
Y

tensor([[0.7266, 0.9671, 0.2545, 0.5880],
        [0.4078, 0.0173, 0.7358, 0.3279]])

# Converting `Torch` $\rightarrow$ `Numpy`

In [151]:
X = Y.numpy()
X

array([[0.7266455 , 0.9670757 , 0.25453675, 0.5879673 ],
       [0.40776455, 0.01727426, 0.73584735, 0.32792306]], dtype=float32)

____

## Using GPUs 

Using **GPU** in pytorch is as simple as calling **`.cuda()`** on your tensor.

But first, you may want to check: 
 - that cuda can actually be used : `torch.cuda.is_available()`
 - how many gpus are available : `torch.cuda.device_count()`

In [152]:
torch.cuda.is_available()

False

In [153]:
torch.cuda.device_count()

0

In [154]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### tensor.cuda

_Note : If you don't have Cuda on the machine, the following examples won't work_

In [155]:
x.cuda(0)
print(x.device)
x = x.cuda(0)
print(x.device)
x = x.cuda(1)
print(x.device)

AssertionError: Torch not compiled with CUDA enabled

In [156]:
x = torch.Tensor([[1,2,3], [4,5,6]])

# This will generate an error since you cannot do operation on tensor that are not on the same device
x + x.cuda()

AssertionError: Torch not compiled with CUDA enabled

#### Write an if statement that moves x on gpu if cuda is available

In [ ]:
# YOUR TURN

These kinds of if statements used to be all over the place in people's pytorch code. Recently, a more flexible way was introduced:

### torch.device

A **`torch.device`** is an object representing the device on which a torch.tensor is or will be allocated.

You can easily move a tensor from a device to another by using the **`tensor.to()`** function

In [ ]:
cpu = torch.device('cpu')
cuda_0 = torch.device('cuda:0')

x = x.to(cpu)
print(x.device)
x = x.to(cuda_0)
print(x.device)

It can be more flexible since you can check if cuda exists only once in your code

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = x.to(device)  # We don't need to care anymore about whether cuda is available or not
print(x.device)

#### Timing GPU

How much faster is GPU ?  See for yourself ...

In [ ]:
A = torch.rand(100, 1000, 1000)
B = A.cuda(1)
A.size()

In [ ]:
%timeit -n 3 torch.bmm(A, A)

In [ ]:
%timeit -n 30 torch.bmm(B, B)